"""PR intelligence brief — heterogeneous review protocol and brief schema.

Implements the type contracts that #6307 (receipt schema), #6304 (UI), and
#6305 (cost controls) all import. This module deliberately contains only
data shapes and enums — no behavior, no I/O, no orchestration. Behavior
ships in successor PRs against the same package.

Design brief: docs/plans/2026-04-19-pr-intelligence-brief.md
Tracking: #6306
"""

from aragora.review.builder import (
    PanelVote,
    build_brief,
    compute_packet_sha,
)
from aragora.review.protocol import (
    ADVISORY_NOTE,
    DissentingView,
    DissentPosition,
    PRReviewProtocol,
    Recommendation,
    ReviewBrief,
    ReviewRole,
    RoleFinding,
    SynthesisPolicy,
)
from aragora.review.policy import (
    BudgetHeadroom,
    BudgetScope,
    CostMeter,
    DepthTrigger,
    ReviewBudget,
    ReviewDepth,
    ReviewPolicy,
    ReviewPolicyDecision,
    RiskClass,
)
from aragora.review.receipt import (
    BriefReceipt,
    EvidenceKind,
    EvidenceRef,
    SettlementAction,
    SettlementLinkage,
    ValidationKind,
    ValidationRef,
    ValidationResult,
)
from aragora.review.provider_slots import (
    ProviderCandidateCheck,
    ProviderSlotAvailabilitySummary,
    ProviderSlotDefinition,
    ProviderSlotResolution,
    ProviderSlotResolver,
)
from aragora.review.reviewer_output import (
    FindingCategory,
    FindingSeverity,
    REVIEWER_OUTPUT_SCHEMA_VERSION,
    ReviewerFinding,
    ReviewerOutput,
    validate_reviewer_outputs,
)
from aragora.review.invalidation import (
    DEFAULT_BASELINE_WINDOW_DAYS,
    DEFAULT_MIN_BASELINE_SAMPLES,
    DEFAULT_REVERT_WINDOW_DAYS,
    DEFAULT_SAFETY_MARGIN,
    DEFAULT_MINIMUM_MEANINGFUL_RATE,
    INVALIDATION_HUMAN_OVERRIDE_REDO,
    INVALIDATION_POST_MERGE_INCIDENT,
    INVALIDATION_REOPENED_PR,
    INVALIDATION_REVERT_WITHIN_WINDOW,
    INVALIDATION_ROLLBACK,
    INVALIDATION_SIGNALS,
    BaselineMeasurement,
    InvalidatedDecision,
    ThresholdProposal,
    classify_invalidation,
    compute_baseline,
    derive_threshold,
    is_invalidated,
)
from aragora.review.invalidation_event_source import (
    ReviewQueueInvalidationEventSource,
    count_decisions_from_settlement_receipts,
    iter_invalidations_from_calibration_store,
    iter_invalidations_from_settlement_receipts,
    measure_baseline_from_stores,
    resolve_review_queue_root,
)
from aragora.review.threshold_recalibration import (
    DEFAULT_THRESHOLD_RECEIPT_DIR,
    DEFAULT_SUPPORT_TARGETS,
    INSUFFICIENCY_RECEIPT_SCHEMA_VERSION,
    THRESHOLD_UPDATE_RECEIPT_SCHEMA_VERSION,
    InsufficiencyReceipt,
    InvalidationEventSource,
    InvalidationRecalibrationSample,
    RecalibrationReceipt,
    ThresholdRecalibrationScheduler,
    ThresholdUpdateReceipt,
    compute_insufficiency_receipt_id,
    compute_threshold_update_receipt_id,
    write_insufficiency_receipt,
    write_recalibration_receipt,
    write_threshold_update_receipt,
)

__all__ = [
    "ADVISORY_NOTE",
    "BaselineMeasurement",
    "BriefReceipt",
    "BudgetHeadroom",
    "BudgetScope",
    "CostMeter",
    "DEFAULT_BASELINE_WINDOW_DAYS",
    "DEFAULT_MIN_BASELINE_SAMPLES",
    "DEFAULT_MINIMUM_MEANINGFUL_RATE",
    "DEFAULT_REVERT_WINDOW_DAYS",
    "DEFAULT_SAFETY_MARGIN",
    "DEFAULT_SUPPORT_TARGETS",
    "DEFAULT_THRESHOLD_RECEIPT_DIR",
    "DepthTrigger",
    "DissentingView",
    "DissentPosition",
    "EvidenceKind",
    "EvidenceRef",
    "FindingCategory",
    "FindingSeverity",
    "INVALIDATION_HUMAN_OVERRIDE_REDO",
    "INVALIDATION_POST_MERGE_INCIDENT",
    "INVALIDATION_REOPENED_PR",
    "INVALIDATION_REVERT_WITHIN_WINDOW",
    "INVALIDATION_ROLLBACK",
    "INVALIDATION_SIGNALS",
    "INSUFFICIENCY_RECEIPT_SCHEMA_VERSION",
    "InsufficiencyReceipt",
    "InvalidationEventSource",
    "InvalidationRecalibrationSample",
    "InvalidatedDecision",
    "PRReviewProtocol",
    "ProviderCandidateCheck",
    "ProviderSlotAvailabilitySummary",
    "ProviderSlotDefinition",
    "ProviderSlotResolution",
    "ProviderSlotResolver",
    "PanelVote",
    "REVIEWER_OUTPUT_SCHEMA_VERSION",
    "Recommendation",
    "RecalibrationReceipt",
    "ReviewBrief",
    "ReviewBudget",
    "ReviewDepth",
    "ReviewerFinding",
    "ReviewerOutput",
    "ReviewPolicy",
    "ReviewPolicyDecision",
    "ReviewQueueInvalidationEventSource",
    "ReviewRole",
    "RiskClass",
    "RoleFinding",
    "SettlementAction",
    "SettlementLinkage",
    "SynthesisPolicy",
    "ThresholdProposal",
    "ThresholdRecalibrationScheduler",
    "ThresholdUpdateReceipt",
    "THRESHOLD_UPDATE_RECEIPT_SCHEMA_VERSION",
    "ValidationKind",
    "ValidationRef",
    "ValidationResult",
    "build_brief",
    "classify_invalidation",
    "compute_baseline",
    "compute_insufficiency_receipt_id",
    "compute_packet_sha",
    "compute_threshold_update_receipt_id",
    "count_decisions_from_settlement_receipts",
    "derive_threshold",
    "is_invalidated",
    "iter_invalidations_from_calibration_store",
    "iter_invalidations_from_settlement_receipts",
    "measure_baseline_from_stores",
    "resolve_review_queue_root",
    "validate_reviewer_outputs",
    "write_insufficiency_receipt",
    "write_recalibration_receipt",
    "write_threshold_update_receipt",
]
