"""
Unified Inbox OpenAPI Schema Definitions.

Schemas for shared inboxes and routing rules.
"""

from typing import Any

INBOX_SCHEMAS: dict[str, Any] = {
    "SharedInbox": {
        "type": "object",
        "properties": {
            "id": {"type": "string"},
            "workspace_id": {"type": "string"},
            "name": {"type": "string"},
            "description": {"type": ["string", "null"]},
            "email_address": {"type": ["string", "null"]},
            "connector_type": {"type": ["string", "null"]},
            "team_members": {"type": "array", "items": {"type": "string"}},
            "admins": {"type": "array", "items": {"type": "string"}},
            "message_count": {"type": "integer"},
            "unread_count": {"type": "integer"},
            "settings": {"type": "object"},
            "created_at": {"type": "string"},
            "updated_at": {"type": "string"},
            "created_by": {"type": ["string", "null"]},
        },
    },
    "SharedInboxMessage": {
        "type": "object",
        "properties": {
            "id": {"type": "string"},
            "inbox_id": {"type": "string"},
            "email_id": {"type": "string"},
            "subject": {"type": "string"},
            "from_address": {"type": "string"},
            "to_addresses": {"type": "array", "items": {"type": "string"}},
            "snippet": {"type": "string"},
            "received_at": {"type": "string"},
            "status": {"type": "string"},
            "assigned_to": {"type": ["string", "null"]},
            "tags": {"type": "array", "items": {"type": "string"}},
            "priority": {"type": ["string", "null"]},
        },
    },
    "SharedInboxResponse": {
        "type": "object",
        "properties": {
            "success": {"type": "boolean"},
            "inbox": {"$ref": "#/components/schemas/SharedInbox"},
            "error": {"type": ["string", "null"]},
        },
        "required": ["success"],
    },
    "SharedInboxListResponse": {
        "type": "object",
        "properties": {
            "success": {"type": "boolean"},
            "inboxes": {"type": "array", "items": {"$ref": "#/components/schemas/SharedInbox"}},
            "total": {"type": "integer"},
        },
        "required": ["success", "inboxes", "total"],
    },
    "SharedInboxMessageListResponse": {
        "type": "object",
        "properties": {
            "success": {"type": "boolean"},
            "messages": {
                "type": "array",
                "items": {"$ref": "#/components/schemas/SharedInboxMessage"},
            },
            "total": {"type": "integer"},
            "limit": {"type": "integer"},
            "offset": {"type": "integer"},
        },
        "required": ["success", "messages", "total"],
    },
    "SharedInboxMessageResponse": {
        "type": "object",
        "properties": {
            "success": {"type": "boolean"},
            "message": {"$ref": "#/components/schemas/SharedInboxMessage"},
            "error": {"type": ["string", "null"]},
        },
        "required": ["success"],
    },
    "SharedInboxCreateRequest": {
        "type": "object",
        "properties": {
            "workspace_id": {"type": "string"},
            "name": {"type": "string"},
            "description": {"type": "string"},
            "email_address": {"type": "string"},
            "connector_type": {"type": "string"},
            "team_members": {"type": "array", "items": {"type": "string"}},
            "admins": {"type": "array", "items": {"type": "string"}},
            "settings": {"type": "object"},
        },
        "required": ["workspace_id", "name"],
    },
    "SharedInboxAssignRequest": {
        "type": "object",
        "properties": {
            "assigned_to": {"type": "string"},
        },
        "required": ["assigned_to"],
    },
    "SharedInboxStatusRequest": {
        "type": "object",
        "properties": {
            "status": {"type": "string"},
        },
        "required": ["status"],
    },
    "SharedInboxTagRequest": {
        "type": "object",
        "properties": {
            "tag": {"type": "string"},
        },
        "required": ["tag"],
    },
    "RoutingRule": {
        "type": "object",
        "properties": {
            "id": {"type": "string"},
            "workspace_id": {"type": "string"},
            "name": {"type": "string"},
            "conditions": {"type": "array", "items": {"type": "object"}},
            "condition_logic": {"type": "string"},
            "actions": {"type": "array", "items": {"type": "object"}},
            "priority": {"type": "integer"},
            "enabled": {"type": "boolean"},
            "description": {"type": ["string", "null"]},
            "created_at": {"type": "string"},
            "updated_at": {"type": "string"},
            "created_by": {"type": ["string", "null"]},
            "stats": {"type": "object"},
        },
    },
    "RoutingRuleResponse": {
        "type": "object",
        "properties": {
            "success": {"type": "boolean"},
            "rule": {"$ref": "#/components/schemas/RoutingRule"},
            "error": {"type": ["string", "null"]},
        },
        "required": ["success"],
    },
    "RoutingRuleListResponse": {
        "type": "object",
        "properties": {
            "success": {"type": "boolean"},
            "rules": {"type": "array", "items": {"$ref": "#/components/schemas/RoutingRule"}},
            "total": {"type": "integer"},
            "limit": {"type": "integer"},
            "offset": {"type": "integer"},
        },
        "required": ["success", "rules", "total"],
    },
    "RoutingRuleDeleteResponse": {
        "type": "object",
        "properties": {
            "success": {"type": "boolean"},
            "deleted": {"type": "string"},
        },
        "required": ["success"],
    },
    "RoutingRuleTestResponse": {
        "type": "object",
        "properties": {
            "success": {"type": "boolean"},
            "rule_id": {"type": "string"},
            "match_count": {"type": "integer"},
            "rule": {"$ref": "#/components/schemas/RoutingRule"},
            "error": {"type": ["string", "null"]},
        },
        "required": ["success"],
    },
    "RoutingRuleCreateRequest": {
        "type": "object",
        "properties": {
            "workspace_id": {"type": "string"},
            "name": {"type": "string"},
            "conditions": {"type": "array", "items": {"type": "object"}},
            "condition_logic": {"type": "string"},
            "actions": {"type": "array", "items": {"type": "object"}},
            "priority": {"type": "integer"},
            "enabled": {"type": "boolean"},
            "description": {"type": "string"},
        },
        "required": ["workspace_id", "name", "conditions", "actions"],
    },
    "RoutingRuleUpdateRequest": {
        "type": "object",
        "properties": {
            "name": {"type": "string"},
            "description": {"type": "string"},
            "conditions": {"type": "array", "items": {"type": "object"}},
            "condition_logic": {"type": "string"},
            "actions": {"type": "array", "items": {"type": "object"}},
            "priority": {"type": "integer"},
            "enabled": {"type": "boolean"},
        },
    },
    "RoutingRuleTestRequest": {
        "type": "object",
        "properties": {
            "workspace_id": {"type": "string"},
        },
        "required": ["workspace_id"],
    },
    "InboxTrustWedgePersistedReceipt": {
        "type": "object",
        "properties": {
            "receipt_id": {"type": "string"},
            "intent_hash": {"type": "string"},
            "signature": {"type": "string"},
            "signing_key_id": {"type": "string"},
            "state": {
                "type": "string",
                "enum": ["created", "approved", "executed", "expired"],
            },
            "created_at": {"type": "string", "format": "date-time"},
            "expires_at": {"type": ["string", "null"], "format": "date-time"},
            "approved_at": {"type": ["string", "null"], "format": "date-time"},
            "executed_at": {"type": ["string", "null"], "format": "date-time"},
            "execution_count": {"type": "integer"},
            "last_error": {"type": ["string", "null"]},
            "canonical_receipt_id": {"type": ["string", "null"]},
        },
        "required": [
            "receipt_id",
            "intent_hash",
            "signature",
            "signing_key_id",
            "state",
            "created_at",
            "execution_count",
        ],
    },
    "InboxTrustWedgeActionIntent": {
        "type": "object",
        "properties": {
            "provider": {"type": "string"},
            "message_id": {"type": "string"},
            "action": {"type": "string", "enum": ["archive", "star", "label", "ignore"]},
            "content_hash": {"type": "string"},
            "synthesized_rationale": {"type": "string"},
            "confidence": {"type": "number"},
            "provider_route": {"type": "string"},
            "debate_id": {"type": ["string", "null"]},
            "label_id": {"type": ["string", "null"]},
            "user_id": {"type": ["string", "null"]},
            "email_subject": {"type": "string"},
            "email_from": {"type": "string"},
            "email_snippet": {"type": "string"},
        },
        "required": [
            "provider",
            "message_id",
            "action",
            "content_hash",
            "synthesized_rationale",
            "confidence",
            "provider_route",
        ],
    },
    "InboxTrustWedgeTriageDecision": {
        "type": "object",
        "properties": {
            "final_action": {"type": "string", "enum": ["archive", "star", "label", "ignore"]},
            "confidence": {"type": "number"},
            "dissent_summary": {"type": "string"},
            "receipt_id": {"type": ["string", "null"]},
            "auto_approval_eligible": {"type": "boolean"},
            "receipt_state": {"type": "string"},
            "provider_route": {"type": "string"},
            "label_id": {"type": ["string", "null"]},
            "blocked_by_policy": {"type": "boolean"},
            "cost_usd": {"type": ["number", "null"]},
            "latency_seconds": {"type": ["number", "null"]},
            "execution_tier": {"type": "string"},
            "escalation_reasons": {"type": "array", "items": {"type": "string"}},
            "suppressed_diagnostics_count": {"type": "integer"},
            "intent": {"$ref": "#/components/schemas/InboxTrustWedgeActionIntent"},
        },
        "required": [
            "final_action",
            "confidence",
            "dissent_summary",
            "auto_approval_eligible",
            "receipt_state",
            "provider_route",
            "blocked_by_policy",
            "execution_tier",
            "escalation_reasons",
            "suppressed_diagnostics_count",
        ],
    },
    "InboxTrustWedgeEnvelope": {
        "type": "object",
        "properties": {
            "intent": {"$ref": "#/components/schemas/InboxTrustWedgeActionIntent"},
            "decision": {"$ref": "#/components/schemas/InboxTrustWedgeTriageDecision"},
            "receipt": {"$ref": "#/components/schemas/InboxTrustWedgePersistedReceipt"},
            "signed_receipt": {"type": "object", "additionalProperties": True},
            "provider_route": {"type": "string"},
            "debate_id": {"type": ["string", "null"]},
            "review_choice": {"type": ["string", "null"]},
            "execution_result": {
                "type": ["object", "null"],
                "additionalProperties": True,
            },
        },
        "required": ["intent", "decision", "receipt", "signed_receipt", "provider_route"],
    },
    "InboxTrustWedgeReceiptListResponse": {
        "type": "object",
        "properties": {
            "receipts": {
                "type": "array",
                "items": {"$ref": "#/components/schemas/InboxTrustWedgeEnvelope"},
            },
            "count": {"type": "integer"},
            "requested_by": {"type": ["string", "null"]},
        },
        "required": ["receipts", "count"],
    },
    "InboxTrustWedgeActionResponse": {
        "type": "object",
        "properties": {
            "message_id": {"type": "string"},
            "action": {"type": "string"},
            "success": {"type": "boolean"},
            "receipt": {"$ref": "#/components/schemas/InboxTrustWedgePersistedReceipt"},
            "intent": {"$ref": "#/components/schemas/InboxTrustWedgeActionIntent"},
            "decision": {"$ref": "#/components/schemas/InboxTrustWedgeTriageDecision"},
            "provider_route": {"type": "string"},
            "debate_id": {"type": ["string", "null"]},
            "requires_approval": {"type": "boolean"},
            "executed": {"type": "boolean"},
            "execution_result": {
                "type": ["object", "null"],
                "additionalProperties": True,
            },
        },
        "required": [
            "message_id",
            "action",
            "success",
            "receipt",
            "intent",
            "decision",
            "provider_route",
            "requires_approval",
            "executed",
        ],
    },
    "InboxTrustWedgeCreateReceiptRequest": {
        "type": "object",
        "properties": {
            "provider": {"type": "string", "default": "gmail"},
            "user_id": {"type": "string"},
            "message_id": {"type": "string"},
            "action": {"type": "string", "enum": ["archive", "star", "label", "ignore"]},
            "content_hash": {"type": "string"},
            "subject": {"type": "string"},
            "snippet": {"type": "string"},
            "body": {"type": "string"},
            "preview": {"type": "string"},
            "message_text": {"type": "string"},
            "synthesized_rationale": {"type": "string"},
            "rationale": {"type": "string"},
            "reason": {"type": "string"},
            "confidence": {"type": "number"},
            "debate_confidence": {"type": "number"},
            "provider_route": {"type": "string"},
            "debate_id": {"type": "string"},
            "label_id": {"type": "string"},
            "labels": {"type": "array", "items": {"type": "string"}},
            "blocked_by_policy": {"type": "boolean"},
            "cost_usd": {"type": "number"},
            "latency_seconds": {"type": "number"},
            "expires_in_hours": {"type": "number"},
            "auto_approve": {"type": "boolean"},
            "auto_execute": {"type": "boolean"},
        },
        "required": ["message_id", "action"],
    },
    "InboxTrustWedgeReviewRequest": {
        "type": "object",
        "properties": {
            "choice": {"type": "string", "enum": ["approve", "reject", "edit", "skip"]},
            "action": {"type": "string", "enum": ["archive", "star", "label", "ignore"]},
            "synthesized_rationale": {"type": "string"},
            "rationale": {"type": "string"},
            "label_id": {"type": "string"},
            "labels": {"type": "array", "items": {"type": "string"}},
            "execute": {"type": "boolean"},
        },
        "required": ["choice"],
    },
}


__all__ = ["INBOX_SCHEMAS"]
