from __future__ import annotations

from types import SimpleNamespace

from aragora.server.handler_registry.core import RouteIndex
from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.admin.feature_flags import FeatureFlagAdminHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_feature_flag_admin_handler_participates_in_all_handlers() -> None:
    assert FeatureFlagAdminHandler in set(ALL_HANDLERS)


def test_route_index_dispatches_admin_feature_flag_routes() -> None:
    holder = SimpleNamespace(_feature_flag_admin_handler=FeatureFlagAdminHandler(ctx={}))
    route_index = RouteIndex()
    route_index.build(
        holder,
        [
            ("_feature_flag_admin_handler", FeatureFlagAdminHandler),
        ],
    )

    def handler_name(path: str) -> str:
        match = route_index.get_handler(path)
        assert match is not None
        return match[0]

    assert handler_name("/api/v1/admin/feature-flags") == "_feature_flag_admin_handler"
    assert handler_name("/api/v1/admin/feature-flags/enable_checkpointing") == (
        "_feature_flag_admin_handler"
    )
    assert handler_name("/api/admin/feature-flags") == "_feature_flag_admin_handler"
    assert handler_name("/api/admin/feature-flags/enable_checkpointing") == (
        "_feature_flag_admin_handler"
    )


def test_admin_feature_flag_openapi_uses_curated_operations() -> None:
    paths = generate_openapi_schema()["paths"]

    base_expected = {
        "/api/v1/admin/feature-flags": (
            "adminListFeatureFlags",
            "updateAdminFeatureFlags",
        ),
        "/api/admin/feature-flags": (
            "adminListFeatureFlagsLegacy",
            "updateAdminFeatureFlagsLegacy",
        ),
    }
    for path, (get_operation_id, put_operation_id) in base_expected.items():
        path_spec = paths[path]
        assert _operation_methods(path_spec) == {"get", "put"}
        get_operation = path_spec["get"]
        assert get_operation["summary"] == "List admin feature flags"
        assert get_operation["operationId"] == get_operation_id
        assert get_operation.get("x-autogenerated") is not True
        put_operation = path_spec["put"]
        assert put_operation["summary"] == "Update admin feature flags"
        assert put_operation["operationId"] == put_operation_id
        assert put_operation.get("x-autogenerated") is not True

    detail_expected = {
        "/api/v1/admin/feature-flags/{name}": (
            "adminGetFeatureFlag",
            "adminSetFeatureFlag",
        ),
        "/api/admin/feature-flags/{name}": (
            "adminGetFeatureFlagLegacy",
            "adminSetFeatureFlagLegacy",
        ),
    }
    for path, (get_operation_id, put_operation_id) in detail_expected.items():
        path_spec = paths[path]
        assert _operation_methods(path_spec) == {"get", "put"}
        assert path_spec["get"]["summary"] == "Get admin feature flag"
        assert path_spec["get"]["operationId"] == get_operation_id
        assert path_spec["get"].get("x-autogenerated") is not True
        assert path_spec["put"]["summary"] == "Set admin feature flag"
        assert path_spec["put"]["operationId"] == put_operation_id
        assert path_spec["put"].get("x-autogenerated") is not True

    assert paths["/api/admin/feature-flags"]["get"]["deprecated"] is True
    assert paths["/api/admin/feature-flags"]["put"]["deprecated"] is True
    assert paths["/api/admin/feature-flags/{name}"]["get"]["deprecated"] is True
    assert paths["/api/admin/feature-flags/{name}"]["put"]["deprecated"] is True
    assert "/api/v1/admin/feature-flags/{param}" not in paths
    assert "/api/admin/feature-flags/{param}" not in paths
