from __future__ import annotations

from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.tasks.queue import TaskQueueHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_task_queue_handler_participates_in_all_handlers() -> None:
    assert TaskQueueHandler in set(ALL_HANDLERS)


def test_task_queue_handler_declares_explicit_public_routes() -> None:
    assert set(TaskQueueHandler.ROUTES) == {
        "/api/v1/tasks/queue",
        "/api/v1/tasks/queue/stats",
        "/api/v1/tasks/queue/{task_id}",
        "/api/v1/tasks/queue/sync",
        "/api/v1/tasks/queue/{task_id}/claim",
        "/api/v1/tasks/leases",
        "/api/v1/tasks/leases/{lease_id}/heartbeat",
        "/api/v1/tasks/leases/{lease_id}/release",
        "/api/v1/tasks/leases/{lease_id}/complete",
        "/api/v1/tasks/salvage",
    }


def test_task_queue_routes_appear_in_generated_openapi_with_declared_methods() -> None:
    paths = generate_openapi_schema()["paths"]

    expected_methods = {
        "/api/v1/tasks/queue": {"get"},
        "/api/v1/tasks/queue/stats": {"get"},
        "/api/v1/tasks/queue/{task_id}": {"get"},
        "/api/v1/tasks/queue/sync": {"post"},
        "/api/v1/tasks/queue/{task_id}/claim": {"post"},
        "/api/v1/tasks/leases": {"get"},
        "/api/v1/tasks/leases/{lease_id}/heartbeat": {"post"},
        "/api/v1/tasks/leases/{lease_id}/release": {"post"},
        "/api/v1/tasks/leases/{lease_id}/complete": {"post"},
        "/api/v1/tasks/salvage": {"get"},
    }

    for path, methods in expected_methods.items():
        assert path in paths
        assert _operation_methods(paths[path]) == methods
        for method in methods:
            assert paths[path][method].get("x-autogenerated") is not True


def test_task_queue_base_paths_do_not_export_autogenerated_post_placeholders() -> None:
    paths = generate_openapi_schema()["paths"]

    for path in (
        "/api/v1/tasks/queue",
        "/api/v1/tasks/leases",
        "/api/v1/tasks/salvage",
    ):
        assert "post" not in paths[path]
        assert paths[path]["get"].get("x-autogenerated") is not True
