from __future__ import annotations

from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_orchestration_v1_compat_routes_use_curated_exports() -> None:
    paths = generate_openapi_schema()["paths"]
    required_security = [{"bearerAuth": []}]

    status_spec = paths["/api/v1/orchestration/status/{request_id}"]
    status_get = status_spec["get"]
    assert _operation_methods(status_spec) == {"get"}
    assert status_get["summary"] == "Get deliberation status (v1 compatibility)"
    assert status_get["operationId"] == "getOrchestrationDeliberationStatusV1Compat"
    assert status_get.get("x-autogenerated") is not True
    assert status_get["security"] == required_security
    assert status_get["parameters"][0]["name"] == "request_id"

    templates_spec = paths["/api/v1/orchestration/templates"]
    templates_get = templates_spec["get"]
    assert _operation_methods(templates_spec) == {"get"}
    assert templates_get["summary"] == "List orchestration templates (v1 compatibility)"
    assert templates_get["operationId"] == "listOrchestrationTemplatesV1Compat"
    assert templates_get.get("x-autogenerated") is not True
    assert templates_get["security"] == required_security

    assert "/api/v1/orchestration/status" not in paths
