from __future__ import annotations

from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.debates.handler import DebatesHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_debates_handler_participates_in_all_handlers() -> None:
    assert DebatesHandler in set(ALL_HANDLERS)


def test_active_debates_route_uses_curated_get_operation() -> None:
    paths = generate_openapi_schema()["paths"]

    operation = paths["/api/v1/debates/active"]["get"]
    assert _operation_methods(paths["/api/v1/debates/active"]) == {"get"}
    assert operation["operationId"] == "listActiveDebatesV1"
    assert operation["summary"] == "List active debates"
    assert operation.get("x-autogenerated") is not True


def test_active_debates_route_does_not_export_mutating_placeholders() -> None:
    path_spec = generate_openapi_schema()["paths"]["/api/v1/debates/active"]

    assert "post" not in path_spec
    assert "patch" not in path_spec
    assert "delete" not in path_spec
