from __future__ import annotations

from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.ralph_dashboard import RalphDashboardHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_ralph_dashboard_handler_participates_in_all_handlers() -> None:
    assert RalphDashboardHandler in set(ALL_HANDLERS)


def test_ralph_dashboard_routes_appear_in_generated_openapi() -> None:
    paths = generate_openapi_schema()["paths"]

    assert _operation_methods(paths["/api/v1/ralph/overview"]) == {"get"}
    assert _operation_methods(paths["/api/v1/ralph/blockers"]) == {"get"}
    assert _operation_methods(paths["/api/v1/ralph/campaigns"]) == {"get"}


def test_ralph_dashboard_routes_use_curated_operations() -> None:
    paths = generate_openapi_schema()["paths"]

    for legacy_path in (
        "/api/ralph/overview",
        "/api/ralph/blockers",
        "/api/ralph/campaigns",
    ):
        for path in (legacy_path, legacy_path.replace("/api/", "/api/v1/", 1)):
            for method in _operation_methods(paths[path]):
                operation = paths[path][method]
                assert isinstance(operation, dict)
                assert operation.get("x-autogenerated") is not True
                assert operation["tags"] == ["Ralph"]
                if path.startswith("/api/v1/"):
                    assert operation["operationId"]
