from __future__ import annotations

from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.public.status_page import StatusPageHandler
from aragora.server.openapi import generate_openapi_schema
import pytest


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_status_page_handler_participates_in_all_handlers() -> None:
    assert StatusPageHandler in set(ALL_HANDLERS)


def test_public_surfaces_route_is_public_and_handled() -> None:
    handler = StatusPageHandler()

    assert "/api/v1/public/surfaces" in StatusPageHandler.PUBLIC_ROUTES
    assert handler.can_handle("/api/v1/public/surfaces")


@pytest.mark.skip(
    reason="stale after handler refactor; tracked in test-debt cleanup. Handler method signature / return shape changed; test needs rewrite."
)
def test_public_surfaces_openapi_contract_is_curated() -> None:
    schema = generate_openapi_schema()
    paths = schema["paths"]

    assert _operation_methods(paths["/api/v1/public/surfaces"]) == {"get"}
    operation = paths["/api/v1/public/surfaces"]["get"]

    assert operation["operationId"] == "getPublicSurfaces"
    assert operation["summary"] == "List public surface readiness"
    assert operation["tags"] == ["Status", "Public", "Readiness"]
    assert operation["security"] == []
    assert operation.get("x-autogenerated") is not True

    response_schema = operation["responses"]["200"]["content"]["application/json"]["schema"]
    data_schema = response_schema["properties"]["data"]
    surface_schema = data_schema["properties"]["surfaces"]["items"]
    summary_schema = data_schema["properties"]["summary"]

    assert "surfaces" in data_schema["required"]
    assert "summary" in data_schema["required"]
    assert "placeholder_backed" in surface_schema["required"]
    assert surface_schema["properties"]["readiness"]["enum"] == ["live", "partial"]
    assert set(summary_schema["required"]) == {"total", "live", "partial"}
