from __future__ import annotations

from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.self_improve_details import SelfImproveDetailsHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "options", "head"}


def _operation_methods(paths: dict[str, dict[str, object]], path: str) -> set[str]:
    return {method for method in paths[path] if method in HTTP_METHODS}


def test_self_improve_details_handler_participates_in_all_handlers() -> None:
    assert SelfImproveDetailsHandler in set(ALL_HANDLERS)


def test_self_improve_details_routes_appear_in_generated_openapi() -> None:
    schema = generate_openapi_schema()
    paths = schema["paths"]

    required = {
        "/api/self-improve/meta-planner/goals",
        "/api/self-improve/execution/timeline",
        "/api/self-improve/learning/insights",
        "/api/self-improve/metrics/comparison",
        "/api/self-improve/trends/cycles",
        "/api/self-improve/improvement-queue",
        "/api/self-improve/improvement-queue/{id}/priority",
        "/api/self-improve/improvement-queue/{id}",
        "/api/v1/self-improve/meta-planner/goals",
        "/api/v1/self-improve/improvement-queue",
        "/api/v1/self-improve/improvement-queue/{id}/priority",
        "/api/v1/self-improve/improvement-queue/{id}",
    }

    assert required <= set(paths)


def test_self_improve_details_route_methods_are_preserved() -> None:
    schema = generate_openapi_schema()
    paths = schema["paths"]

    for path in (
        "/api/self-improve/meta-planner/goals",
        "/api/self-improve/execution/timeline",
        "/api/self-improve/learning/insights",
        "/api/self-improve/metrics/comparison",
        "/api/self-improve/trends/cycles",
        "/api/v1/self-improve/meta-planner/goals",
    ):
        assert _operation_methods(paths, path) == {"get"}

    for path in (
        "/api/self-improve/improvement-queue",
        "/api/v1/self-improve/improvement-queue",
    ):
        assert _operation_methods(paths, path) == {"post"}

    for path in (
        "/api/self-improve/improvement-queue/{id}/priority",
        "/api/v1/self-improve/improvement-queue/{id}/priority",
    ):
        assert _operation_methods(paths, path) == {"put"}

    for path in (
        "/api/self-improve/improvement-queue/{id}",
        "/api/v1/self-improve/improvement-queue/{id}",
    ):
        assert _operation_methods(paths, path) == {"delete"}


def test_self_improve_details_routes_are_curated_not_placeholders() -> None:
    schema = generate_openapi_schema()
    paths = schema["paths"]

    expected_methods = {
        "/api/self-improve/meta-planner/goals": {"get"},
        "/api/self-improve/execution/timeline": {"get"},
        "/api/self-improve/learning/insights": {"get"},
        "/api/self-improve/metrics/comparison": {"get"},
        "/api/self-improve/trends/cycles": {"get"},
        "/api/self-improve/improvement-queue": {"post"},
        "/api/self-improve/improvement-queue/{id}/priority": {"put"},
        "/api/self-improve/improvement-queue/{id}": {"delete"},
        "/api/v1/self-improve/meta-planner/goals": {"get"},
        "/api/v1/self-improve/execution/timeline": {"get"},
        "/api/v1/self-improve/learning/insights": {"get"},
        "/api/v1/self-improve/metrics/comparison": {"get"},
        "/api/v1/self-improve/trends/cycles": {"get"},
        "/api/v1/self-improve/improvement-queue": {"post"},
        "/api/v1/self-improve/improvement-queue/{id}/priority": {"put"},
        "/api/v1/self-improve/improvement-queue/{id}": {"delete"},
    }

    for path, methods in expected_methods.items():
        assert path in paths
        assert _operation_methods(paths, path) == methods
        for method in methods:
            assert paths[path][method].get("x-autogenerated") is not True
