from __future__ import annotations

from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.admin.rotation_status import RotationStatusHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_rotation_status_handler_participates_in_all_handlers() -> None:
    assert RotationStatusHandler in set(ALL_HANDLERS)


def test_rotation_status_routes_export_curated_get_operations() -> None:
    paths = generate_openapi_schema()["paths"]

    expected = {
        "/api/v1/admin/security/rotation-status": "adminGetRotationStatus",
        "/api/admin/security/rotation-status": "adminGetRotationStatusLegacy",
    }

    for path, operation_id in expected.items():
        assert _operation_methods(paths[path]) == {"get"}
        operation = paths[path]["get"]
        assert operation["operationId"] == operation_id
        assert operation["summary"] == "Get key rotation status"
        assert operation.get("x-autogenerated") is not True

    assert paths["/api/admin/security/rotation-status"]["get"]["deprecated"] is True
