from __future__ import annotations

from aragora.server.openapi import generate_openapi_schema


def test_feedback_hub_routes_use_curated_get_metadata() -> None:
    schema = generate_openapi_schema()
    paths = schema["paths"]

    expected = {
        "/api/feedback-hub/stats": None,
        "/api/feedback-hub/history": None,
        "/api/v1/feedback-hub/stats": "getFeedbackHubStatsV1",
        "/api/v1/feedback-hub/history": "listFeedbackHubHistoryV1",
    }

    for path, operation_id in expected.items():
        assert set(paths[path]) == {"get"}
        operation = paths[path]["get"]
        if operation_id is None:
            assert "operationId" not in operation
        else:
            assert operation["operationId"] == operation_id
        assert operation["tags"] == ["Feedback Hub"]
        assert operation.get("x-autogenerated") is not True


def test_feedback_hub_history_documents_limit_parameter() -> None:
    schema = generate_openapi_schema()
    paths = schema["paths"]

    for path in ("/api/feedback-hub/history", "/api/v1/feedback-hub/history"):
        parameters = paths[path]["get"]["parameters"]
        limit = next(param for param in parameters if param["name"] == "limit")
        assert limit["in"] == "query"
        assert limit["description"]
        assert limit["schema"] == {
            "type": "integer",
            "minimum": 1,
            "maximum": 200,
            "default": 50,
        }
