from __future__ import annotations

from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.mcp_tools_handler import MCPToolsHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_mcp_tools_handler_participates_in_all_handlers() -> None:
    assert MCPToolsHandler in set(ALL_HANDLERS)


def test_mcp_tools_openapi_uses_curated_operations() -> None:
    paths = generate_openapi_schema()["paths"]

    list_operation = paths["/api/v1/mcp/tools"]["get"]
    assert _operation_methods(paths["/api/v1/mcp/tools"]) == {"get"}
    assert list_operation["summary"] == "List MCP tools"
    assert list_operation["operationId"] == "listMcpToolsV1"
    assert list_operation.get("x-autogenerated") is not True
    assert list_operation["parameters"] == [
        {
            "name": "category",
            "in": "query",
            "required": False,
            "description": "Optional tool-name prefix filter.",
            "schema": {"type": "string"},
        }
    ]

    detail_operation = paths["/api/v1/mcp/tools/{name}"]["get"]
    assert _operation_methods(paths["/api/v1/mcp/tools/{name}"]) == {"get"}
    assert detail_operation["summary"] == "Get MCP tool"
    assert detail_operation["operationId"] == "getMcpToolV1"
    assert detail_operation.get("x-autogenerated") is not True
    assert detail_operation["parameters"] == [
        {
            "name": "name",
            "in": "path",
            "required": True,
            "description": "MCP tool name.",
            "schema": {"type": "string"},
        }
    ]

    assert "/api/v1/mcp/tools/{param}" not in paths
