from __future__ import annotations

from aragora.server.openapi import generate_openapi_schema

HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_prompt_engine_openapi_matches_handler_methods() -> None:
    schema = generate_openapi_schema()
    paths = schema["paths"]

    expected_methods = {
        "/api/prompt-engine/runs": {"get"},
        "/api/prompt-engine/runs/{run_id}": {"get"},
        "/api/prompt-engine/run": {"post"},
        "/api/prompt-engine/decompose": {"post"},
        "/api/prompt-engine/interrogate": {"post"},
        "/api/prompt-engine/research": {"post"},
        "/api/prompt-engine/specify": {"post"},
        "/api/prompt-engine/validate": {"post"},
    }

    for legacy_path, methods in expected_methods.items():
        versioned_path = legacy_path.replace("/api/", "/api/v1/", 1)
        assert _operation_methods(paths[legacy_path]) == methods
        assert _operation_methods(paths[versioned_path]) == methods


def test_prompt_engine_openapi_uses_curated_operations() -> None:
    schema = generate_openapi_schema()
    paths = schema["paths"]

    for legacy_path in (
        "/api/prompt-engine/runs",
        "/api/prompt-engine/runs/{run_id}",
        "/api/prompt-engine/run",
        "/api/prompt-engine/decompose",
        "/api/prompt-engine/interrogate",
        "/api/prompt-engine/research",
        "/api/prompt-engine/specify",
        "/api/prompt-engine/validate",
    ):
        for path in (legacy_path, legacy_path.replace("/api/", "/api/v1/", 1)):
            for method in _operation_methods(paths[path]):
                operation = paths[path][method]
                assert isinstance(operation, dict)
                assert operation.get("x-autogenerated") is not True
                assert operation["tags"] == ["Prompt Engine"]
