from __future__ import annotations

from types import SimpleNamespace

from aragora.server.handler_registry.core import RouteIndex
from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.admin.mfa_compliance import MFAComplianceHandler
from aragora.server.handlers.auth.handler import AuthHandler
from aragora.server.openapi import generate_openapi_schema


def test_auth_handler_exports_admin_mfa_compliance_runtime_route() -> None:
    assert AuthHandler in set(ALL_HANDLERS)

    handler = AuthHandler(server_context={})
    assert handler.can_handle("/api/admin/mfa/compliance")
    assert handler.can_handle("/api/v1/admin/mfa/compliance")
    assert not handler.can_handle("/api/v1/admin/mfa-compliance")


def test_route_index_dispatches_public_mfa_compliance_to_auth_handler() -> None:
    holder = SimpleNamespace(
        _auth_handler=AuthHandler(server_context={}),
        _mfa_compliance_handler=MFAComplianceHandler(ctx={}),
    )
    route_index = RouteIndex()
    route_index.build(
        holder,
        [
            ("_auth_handler", AuthHandler),
            ("_mfa_compliance_handler", MFAComplianceHandler),
        ],
    )

    def handler_name(path: str) -> str:
        match = route_index.get_handler(path)
        assert match is not None
        return match[0]

    assert handler_name("/api/admin/mfa/compliance") == "_auth_handler"
    assert handler_name("/api/v1/admin/mfa/compliance") == "_auth_handler"
    assert handler_name("/api/v1/admin/mfa-compliance") == "_mfa_compliance_handler"


def test_admin_mfa_compliance_openapi_uses_curated_operations() -> None:
    paths = generate_openapi_schema()["paths"]

    expected = {
        "/api/v1/admin/mfa/compliance": "adminGetMfaCompliance",
        "/api/admin/mfa/compliance": "adminGetMfaComplianceLegacy",
    }

    for path, operation_id in expected.items():
        operation = paths[path]["get"]
        assert operation["operationId"] == operation_id
        assert operation["summary"] == "Get admin MFA compliance report"
        assert operation["tags"] == ["Admin", "MFA", "Compliance"]
        assert operation.get("x-autogenerated") is not True

    assert paths["/api/admin/mfa/compliance"]["get"]["deprecated"] is True
    assert "/api/v1/admin/mfa-compliance" not in paths
