from __future__ import annotations

from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.agent_evolution_dashboard import AgentEvolutionDashboardHandler
from aragora.server.handlers.chat.router import ChatHandler
from aragora.server.handlers.decision_analytics import DecisionAnalyticsHandler
from aragora.server.handlers.feedback_hub import FeedbackHubHandler
from aragora.server.handlers.outcome_dashboard import OutcomeDashboardHandler
from aragora.server.handlers.system_intelligence import SystemIntelligenceHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_live_dashboard_handlers_participate_in_all_handlers() -> None:
    handlers = set(ALL_HANDLERS)

    assert SystemIntelligenceHandler in handlers
    assert OutcomeDashboardHandler in handlers
    assert AgentEvolutionDashboardHandler in handlers
    assert DecisionAnalyticsHandler in handlers
    assert FeedbackHubHandler in handlers


def test_live_dashboard_routes_appear_in_generated_openapi() -> None:
    schema = generate_openapi_schema()
    paths = schema["paths"]

    assert "/api/v1/system-intelligence/overview" in paths
    assert "/api/v1/outcome-dashboard" in paths
    assert "/api/v1/agent-evolution/timeline" in paths
    assert "/api/v1/decision-analytics/overview" in paths
    assert "/api/v1/decision-analytics/trends" in paths
    assert "/api/v1/decision-analytics/outcomes" in paths
    assert "/api/v1/decision-analytics/agents" in paths
    assert "/api/v1/decision-analytics/domains" in paths
    assert "/api/v1/feedback-hub/stats" in paths
    assert "/api/v1/feedback-hub/history" in paths


def test_decision_analytics_routes_use_handler_metadata_not_placeholders() -> None:
    schema = generate_openapi_schema()
    paths = schema["paths"]

    expected_operations = {
        "/api/v1/decision-analytics/overview": (
            "Get decision analytics overview",
            "handle_get_overview",
        ),
        "/api/v1/decision-analytics/trends": (
            "Get decision quality trends",
            "handle_get_trends",
        ),
        "/api/v1/decision-analytics/outcomes": (
            "Get decision outcomes list",
            "handle_get_outcomes",
        ),
        "/api/v1/decision-analytics/agents": (
            "Get per-agent quality metrics",
            "handle_get_agents",
        ),
        "/api/v1/decision-analytics/domains": (
            "Get quality by domain",
            "handle_get_domains",
        ),
    }

    for path, (summary, operation_id) in expected_operations.items():
        operation = paths[path]["get"]
        assert operation["summary"] == summary
        assert operation["operationId"] == operation_id
        assert operation.get("x-autogenerated") is not True

    assert "/api/decision-analytics/overview" not in paths
    assert "/api/decision-analytics/trends" not in paths
    assert "/api/decision-analytics/outcomes" not in paths
    assert "/api/decision-analytics/agents" not in paths
    assert "/api/decision-analytics/domains" not in paths


def test_chat_handler_participates_in_all_handlers() -> None:
    assert ChatHandler in set(ALL_HANDLERS)


def test_chat_routes_appear_in_generated_openapi_with_declared_methods() -> None:
    schema = generate_openapi_schema()
    paths = schema["paths"]

    webhook_paths = [
        "/api/v1/chat/webhook",
        "/api/v1/chat/slack/webhook",
        "/api/v1/chat/teams/webhook",
        "/api/v1/chat/discord/webhook",
        "/api/v1/chat/google_chat/webhook",
        "/api/v1/chat/telegram/webhook",
        "/api/v1/chat/whatsapp/webhook",
    ]

    assert _operation_methods(paths["/api/v1/chat/status"]) == {"get"}
    for path in webhook_paths:
        assert _operation_methods(paths[path]) == {"post"}
