from __future__ import annotations

from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "options", "head"}


def _operation_methods(paths: dict[str, dict[str, object]], path: str) -> set[str]:
    return {method for method in paths[path] if method in HTTP_METHODS}


def test_settings_api_key_alias_routes_are_curated() -> None:
    paths = generate_openapi_schema()["paths"]

    expected = {
        "/api/api-keys": {
            "get": None,
            "post": None,
            "delete": None,
        },
        "/api/v1/api-keys": {
            "get": "listSettingsApiKeysV1",
            "post": "createSettingsApiKeyV1",
            "delete": "revokeSettingsApiKeyV1",
        },
        "/api/api-keys/{prefix}": {
            "delete": None,
        },
        "/api/v1/api-keys/{prefix}": {
            "delete": "revokeSettingsApiKeyByPrefixV1",
        },
    }

    for path, operations in expected.items():
        assert _operation_methods(paths, path) == set(operations)
        for method, operation_id in operations.items():
            operation = paths[path][method]
            assert isinstance(operation, dict)
            if operation_id is not None:
                assert operation.get("operationId") == operation_id
            assert operation.get("x-autogenerated") is not True
            assert operation["tags"] == ["Authentication", "API Keys"]


def test_auth_api_key_plural_routes_are_curated() -> None:
    paths = generate_openapi_schema()["paths"]

    expected = {
        "/api/auth/api-keys": {
            "get": None,
            "post": None,
            "delete": None,
        },
        "/api/v1/auth/api-keys": {
            "get": "listAuthApiKeysV1",
            "post": "createAuthApiKeyV1",
            "delete": "revokeAuthApiKeyV1",
        },
        "/api/auth/api-keys/{prefix}": {
            "delete": None,
        },
        "/api/v1/auth/api-keys/{prefix}": {
            "delete": "revokeAuthApiKeyByPrefixV1",
        },
    }

    for path, operations in expected.items():
        assert _operation_methods(paths, path) == set(operations)
        for method, operation_id in operations.items():
            operation = paths[path][method]
            assert isinstance(operation, dict)
            if operation_id is not None:
                assert operation.get("operationId") == operation_id
            assert operation.get("x-autogenerated") is not True


def test_auth_api_key_singular_route_does_not_document_unsupported_get() -> None:
    paths = generate_openapi_schema()["paths"]

    assert _operation_methods(paths, "/api/auth/api-key") == {"post", "delete"}
    assert _operation_methods(paths, "/api/v1/auth/api-key") == {"post", "delete"}


def test_api_key_prefix_routes_include_path_parameters() -> None:
    paths = generate_openapi_schema()["paths"]

    for path in (
        "/api/api-keys/{prefix}",
        "/api/v1/api-keys/{prefix}",
        "/api/auth/api-keys/{prefix}",
        "/api/v1/auth/api-keys/{prefix}",
    ):
        operation = paths[path]["delete"]
        assert isinstance(operation, dict)
        parameters = operation.get("parameters")
        assert isinstance(parameters, list)
        assert parameters == [
            {
                "name": "prefix",
                "in": "path",
                "required": True,
                "description": "API key prefix to revoke.",
                "schema": {"type": "string"},
            }
        ]
