from __future__ import annotations

from types import SimpleNamespace

from aragora.server.handler_registry.core import RouteIndex
from aragora.server.handlers.template_marketplace import TemplateRecommendationsHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_template_recommendations_handler_handles_marketplace_route() -> None:
    handler = TemplateRecommendationsHandler(ctx={})
    assert handler.can_handle("/api/v1/marketplace/recommendations")
    assert not handler.can_handle("/api/marketplace/recommendations")


def test_route_index_dispatches_marketplace_recommendations_to_template_handler() -> None:
    holder = SimpleNamespace(
        _template_recommendations_handler=TemplateRecommendationsHandler(ctx={}),
    )
    route_index = RouteIndex()
    route_index.build(
        holder,
        [("_template_recommendations_handler", TemplateRecommendationsHandler)],
    )

    match = route_index.get_handler("/api/v1/marketplace/recommendations")
    assert match is not None
    assert match[0] == "_template_recommendations_handler"
    assert route_index.get_handler("/api/marketplace/recommendations") is None


def test_marketplace_recommendations_openapi_uses_curated_operation() -> None:
    paths = generate_openapi_schema()["paths"]

    operation = paths["/api/v1/marketplace/recommendations"]["get"]
    assert _operation_methods(paths["/api/v1/marketplace/recommendations"]) == {"get"}
    assert operation["summary"] == "Get marketplace recommendations"
    assert operation["operationId"] == "marketplaceGetRecommendations"
    assert operation["tags"] == ["Marketplace"]
    assert operation["security"] == [{"bearerAuth": []}]
    assert operation.get("x-autogenerated") is not True
    assert "401" in operation["responses"]
    assert "403" in operation["responses"]
    assert operation["parameters"][0]["name"] == "limit"
    assert operation["responses"]["200"]["content"]["application/json"]["schema"]["properties"] == {
        "recommendations": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": True,
                "properties": {
                    "id": {"type": "string"},
                    "name": {"type": "string"},
                    "description": {"type": "string"},
                    "category": {"type": "string"},
                    "pattern": {"type": "string"},
                    "author_name": {"type": "string"},
                    "version": {"type": "string"},
                    "tags": {"type": "array", "items": {"type": "string"}},
                    "rating": {"type": "number"},
                    "rating_count": {"type": "integer"},
                    "download_count": {"type": "integer"},
                    "is_featured": {"type": "boolean"},
                    "is_verified": {"type": "boolean"},
                    "created_at": {"type": "number"},
                },
            },
        },
        "total": {"type": "integer"},
    }

    assert "/api/marketplace/recommendations" not in paths
