from __future__ import annotations

from aragora.server.handlers.admin.health.build import BuildInfoHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_build_info_handler_accepts_public_aliases() -> None:
    handler = BuildInfoHandler(ctx={})

    assert handler.can_handle("/health/build")
    assert handler.can_handle("/api/health/build")
    assert handler.can_handle("/api/v1/health/build")


def test_build_info_routes_use_curated_get_operations() -> None:
    paths = generate_openapi_schema()["paths"]

    expected = {
        "/health/build": ("getBuildInfoRoot", False),
        "/api/health/build": ("getBuildInfoLegacy", True),
        "/api/v1/health/build": ("getBuildInfoV1", False),
    }

    for path, (operation_id, deprecated) in expected.items():
        operation = paths[path]["get"]
        assert _operation_methods(paths[path]) == {"get"}
        assert operation["operationId"] == operation_id
        assert operation["summary"] == "Get build information"
        assert operation["tags"] == ["System"]
        assert operation.get("x-autogenerated") is not True
        assert [param["name"] for param in operation["parameters"]] == ["verify"]
        assert bool(operation.get("deprecated")) is deprecated
