from __future__ import annotations

from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.system_health import SystemHealthDashboardHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_system_health_handler_participates_in_all_handlers() -> None:
    assert SystemHealthDashboardHandler in set(ALL_HANDLERS)


def test_admin_system_health_openapi_uses_curated_operations() -> None:
    paths = generate_openapi_schema()["paths"]

    expected = {
        "/api/v1/admin/system-health": (
            "Get admin system health overview",
            "adminGetSystemHealthOverview",
        ),
        "/api/v1/admin/system-health/circuit-breakers": (
            "Get admin system health circuit breakers",
            "adminGetSystemHealthCircuitBreakers",
        ),
        "/api/v1/admin/system-health/slos": (
            "Get admin system health SLOs",
            "adminGetSystemHealthSlos",
        ),
        "/api/v1/admin/system-health/adapters": (
            "Get admin system health adapters",
            "adminGetSystemHealthAdapters",
        ),
        "/api/v1/admin/system-health/agents": (
            "Get admin system health agents",
            "adminGetSystemHealthAgents",
        ),
        "/api/v1/admin/system-health/budget": (
            "Get admin system health budget",
            "adminGetSystemHealthBudget",
        ),
        "/api/admin/system-health": (
            "Get admin system health overview",
            "adminGetSystemHealthOverviewLegacy",
        ),
        "/api/admin/system-health/circuit-breakers": (
            "Get admin system health circuit breakers",
            "adminGetSystemHealthCircuitBreakersLegacy",
        ),
        "/api/admin/system-health/slos": (
            "Get admin system health SLOs",
            "adminGetSystemHealthSlosLegacy",
        ),
        "/api/admin/system-health/adapters": (
            "Get admin system health adapters",
            "adminGetSystemHealthAdaptersLegacy",
        ),
        "/api/admin/system-health/agents": (
            "Get admin system health agents",
            "adminGetSystemHealthAgentsLegacy",
        ),
        "/api/admin/system-health/budget": (
            "Get admin system health budget",
            "adminGetSystemHealthBudgetLegacy",
        ),
    }

    for path, (summary, operation_id) in expected.items():
        operation = paths[path]["get"]
        assert _operation_methods(paths[path]) == {"get"}
        assert operation["summary"] == summary
        assert operation["operationId"] == operation_id
        assert operation.get("x-autogenerated") is not True

    for legacy_path in (
        "/api/admin/system-health",
        "/api/admin/system-health/circuit-breakers",
        "/api/admin/system-health/slos",
        "/api/admin/system-health/adapters",
        "/api/admin/system-health/agents",
        "/api/admin/system-health/budget",
    ):
        assert paths[legacy_path]["get"]["deprecated"] is True

    assert "/api/v1/admin/system-health/{param}" not in paths
    assert "/api/admin/system-health/{param}" not in paths
