from __future__ import annotations

import json
from pathlib import Path

from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.hybrid_debate_handler import HybridDebateHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def test_hybrid_debate_handler_participates_in_all_handlers() -> None:
    assert HybridDebateHandler in set(ALL_HANDLERS)


def test_hybrid_debate_openapi_exports_collection_and_detail_routes() -> None:
    paths = generate_openapi_schema()["paths"]

    collection = paths["/api/v1/debates/hybrid"]
    detail = paths["/api/v1/debates/hybrid/{id}"]

    assert _operation_methods(collection) == {"get", "post"}
    assert collection["get"]["operationId"] == "listHybridDebatesV1"
    assert collection["post"]["operationId"] == "createHybridDebateV1"
    assert collection["get"].get("x-autogenerated") is not True
    assert collection["post"].get("x-autogenerated") is not True

    assert _operation_methods(detail) == {"get"}
    assert detail["get"]["operationId"] == "getHybridDebateV1"
    assert detail["get"]["parameters"][0]["name"] == "id"
    assert detail["get"].get("x-autogenerated") is not True
    assert "/api/v1/debates/hybrid/{param}" not in paths


def test_hybrid_debate_committed_contract_artifacts_include_detail_route() -> None:
    root = _repo_root()
    openapi = json.loads((root / "docs/api/openapi.json").read_text())
    generated = json.loads((root / "docs/api/openapi_generated.json").read_text())
    typescript_types = (root / "sdk/typescript/src/openapi-types.ts").read_text()

    for spec in (openapi, generated):
        paths = spec["paths"]
        assert "/api/v1/debates/hybrid/{id}" in paths
        assert paths["/api/v1/debates/hybrid/{id}"]["get"]["operationId"] == ("getHybridDebateV1")
        assert "/api/v1/debates/hybrid/{param}" not in paths

    assert '"/api/v1/debates/hybrid/{id}"' in typescript_types
    assert 'get: operations["getHybridDebateV1"]' in typescript_types
