from __future__ import annotations

from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_debate_session_cost_routes_use_curated_get_metadata() -> None:
    paths = generate_openapi_schema()["paths"]

    expected_operations = {
        "/api/v1/costs/debates/{debate_id}": "getDebateSessionCosts",
        "/api/v1/costs/debates/{debate_id}/line-items": "listDebateCostLineItems",
        "/api/v1/costs/debates/{debate_id}/performance": "getDebateCostPerformance",
    }

    for path, operation_id in expected_operations.items():
        assert path in paths
        assert _operation_methods(paths[path]) == {"get"}
        operation = paths[path]["get"]
        assert operation["operationId"] == operation_id
        assert operation.get("x-autogenerated") is not True


def test_debate_session_cost_routes_do_not_export_post_placeholders() -> None:
    paths = generate_openapi_schema()["paths"]

    assert "/api/v1/costs/debates" not in paths
    assert "/api/costs/debates" not in paths

    for path in (
        "/api/v1/costs/debates/{debate_id}",
        "/api/v1/costs/debates/{debate_id}/line-items",
        "/api/v1/costs/debates/{debate_id}/performance",
        "/api/costs/debates/{debate_id}",
        "/api/costs/debates/{debate_id}/line-items",
        "/api/costs/debates/{debate_id}/performance",
    ):
        assert path in paths
        assert "post" not in paths[path]
