from __future__ import annotations

from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.marketplace_pilot import MarketplacePilotHandler
from aragora.server.openapi import generate_openapi_schema


HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _operation_methods(path_spec: dict[str, object]) -> set[str]:
    return {method for method in path_spec if method in HTTP_METHODS}


def test_marketplace_pilot_handler_participates_in_all_handlers() -> None:
    assert MarketplacePilotHandler in set(ALL_HANDLERS)


def test_marketplace_pilot_openapi_uses_curated_operations() -> None:
    paths = generate_openapi_schema()["paths"]
    required_security = [{"bearerAuth": []}]

    expected = {
        "/api/v1/marketplace/listings": (
            "get",
            "List marketplace listings",
            "marketplaceListListings",
        ),
        "/api/v1/marketplace/listings/featured": (
            "get",
            "List featured marketplace listings",
            "marketplaceListFeaturedListings",
        ),
        "/api/v1/marketplace/listings/stats": (
            "get",
            "Get marketplace listing stats",
            "marketplaceGetListingStats",
        ),
        "/api/v1/marketplace/listings/{listing_id}": (
            "get",
            "Get marketplace listing",
            "marketplaceGetListing",
        ),
        "/api/v1/marketplace/listings/{listing_id}/install": (
            "post",
            "Install marketplace listing",
            "marketplaceInstallListing",
        ),
        "/api/v1/marketplace/listings/{listing_id}/rate": (
            "post",
            "Rate marketplace listing",
            "marketplaceRateListing",
        ),
        "/api/v1/marketplace/listings/{listing_id}/launch-debate": (
            "post",
            "Launch debate from marketplace listing",
            "marketplaceLaunchDebateFromListing",
        ),
        "/api/marketplace/listings": (
            "get",
            "List marketplace listings",
            "marketplaceListListingsLegacy",
        ),
        "/api/marketplace/listings/featured": (
            "get",
            "List featured marketplace listings",
            "marketplaceListFeaturedListingsLegacy",
        ),
        "/api/marketplace/listings/stats": (
            "get",
            "Get marketplace listing stats",
            "marketplaceGetListingStatsLegacy",
        ),
        "/api/marketplace/listings/{listing_id}": (
            "get",
            "Get marketplace listing",
            "marketplaceGetListingLegacy",
        ),
        "/api/marketplace/listings/{listing_id}/install": (
            "post",
            "Install marketplace listing",
            "marketplaceInstallListingLegacy",
        ),
        "/api/marketplace/listings/{listing_id}/rate": (
            "post",
            "Rate marketplace listing",
            "marketplaceRateListingLegacy",
        ),
        "/api/marketplace/listings/{listing_id}/launch-debate": (
            "post",
            "Launch debate from marketplace listing",
            "marketplaceLaunchDebateFromListingLegacy",
        ),
    }

    for path, (method, summary, operation_id) in expected.items():
        operation = paths[path][method]
        assert _operation_methods(paths[path]) == {method}
        assert operation["summary"] == summary
        assert operation["operationId"] == operation_id
        assert operation.get("x-autogenerated") is not True
        if method == "get":
            assert operation["security"] == required_security
            assert "401" in operation["responses"]
            assert "403" in operation["responses"]

    for legacy_path in (
        "/api/marketplace/listings",
        "/api/marketplace/listings/featured",
        "/api/marketplace/listings/stats",
        "/api/marketplace/listings/{listing_id}",
        "/api/marketplace/listings/{listing_id}/install",
        "/api/marketplace/listings/{listing_id}/rate",
        "/api/marketplace/listings/{listing_id}/launch-debate",
    ):
        operation = next(iter(paths[legacy_path].values()))
        assert operation["deprecated"] is True

    assert "/api/v1/marketplace/listings/{param}" not in paths
    assert "/api/marketplace/listings/{param}" not in paths
