// Auto-generated TypeScript types from OpenAPI specification
// Generated by scripts/generate_typescript_sdk.py
// OpenAPI version: 1.0.0
// Do not edit manually - regenerate from OpenAPI spec

/* eslint-disable @typescript-eslint/no-explicit-any */

export interface Error {
  /** Human-readable error message */
  error: string | null;
  /** Machine-readable error code for programmatic handling */
  code?: "INVALID_JSON" | "MISSING_FIELD" | "INVALID_VALUE" | "AUTH_REQUIRED" | "INVALID_TOKEN" | "FORBIDDEN" | "NOT_OWNER" | "NOT_FOUND" | "QUOTA_EXCEEDED" | "RATE_LIMITED" | "INTERNAL_ERROR" | "SERVICE_UNAVAILABLE" | "AGENT_TIMEOUT" | "CONSENSUS_FAILED" | null;
  /** Unique request ID for debugging and support */
  trace_id?: string;
  /** Name of the field that caused the error (for validation errors) */
  field?: string;
  /** Type of resource involved in the error */
  resource_type?: string;
  /** ID of the resource involved in the error */
  resource_id?: string;
  /** The limit that was exceeded (for quota/rate errors) */
  limit?: number;
  /** Seconds to wait before retrying (for rate limit errors) */
  retry_after?: number;
  /** When the quota/rate limit resets */
  resets_at?: string;
  /** URL to upgrade plan (for quota errors) */
  upgrade_url?: string;
  /** URL for support/issue reporting */
  support_url?: string;
}

export interface PaginatedResponse {
  /** Total items available */
  total?: number;
  /** Current offset */
  offset?: number;
  /** Page size */
  limit?: number;
  /** More items available */
  has_more?: boolean;
}

export interface StandardSuccessResponse {
  success: boolean;
  data?: Record<string, any>;
  message?: string | null;
}

export interface Agent {
  /** Agent name */
  name?: string;
  /** ELO rating */
  elo?: number;
  /** Total matches played */
  matches?: number;
  /** Total wins */
  wins?: number;
  /** Total losses */
  losses?: number;
  /** Calibration accuracy (0-1) */
  calibration_score?: number;
}

export interface HealthCheck {
  status?: "healthy" | "degraded" | "unhealthy";
  version?: string;
  /** Server uptime in seconds */
  uptime_seconds?: number;
  /** Whether the server is in demo mode */
  demo_mode?: boolean;
  timestamp?: string;
  checks?: Record<string, any>;
  response_time_ms?: number;
}

export interface StarterTemplate {
  /** Unique template identifier */
  id: string;
  /** Display name */
  name: string;
  /** Template description */
  description: string;
  /** Applicable use cases */
  use_cases: string[];
  /** Number of agents */
  agents_count: number;
  /** Number of debate rounds */
  rounds: number;
  /** Estimated duration */
  estimated_minutes: number;
  /** Example prompt */
  example_prompt: string;
  /** Categorization tags */
  tags?: string[];
  /** Difficulty level */
  difficulty?: string;
}

export interface GauntletRun {
  /** Run identifier */
  id: string;
  /** Run status */
  status: "pending" | "running" | "completed" | "failed";
  /** Final verdict */
  verdict?: string | null;
  /** Confidence score */
  confidence?: number;
  /** List of findings */
  findings?: Record<string, any>[];
  /** Additional metadata */
  metadata?: Record<string, any>;
  /** Creation timestamp */
  created_at?: string;
  /** Start timestamp */
  started_at?: string | null;
  /** Completion timestamp */
  completed_at?: string | null;
}

export interface GauntletComparison {
  run_a?: GauntletRun;
  run_b?: GauntletRun;
  /** Differences between runs */
  diff?: Record<string, any>;
  /** Similarity percentage */
  similarity_score?: number;
  /** Notes about differences */
  comparison_notes?: string[];
}

export interface Policy {
  /** Policy identifier */
  id: string;
  /** Policy name */
  name: string;
  /** Policy description */
  description?: string;
  /** Policy type */
  type?: string;
  /** Policy rules */
  rules?: Record<string, any>[];
  /** Whether policy is enabled */
  enabled?: boolean;
  /** Execution priority */
  priority?: number;
  /** Creation timestamp */
  created_at?: string;
  /** Last update timestamp */
  updated_at?: string;
}

export type DebateStatus = "created" | "starting" | "pending" | "running" | "in_progress" | "completed" | "failed" | "cancelled" | "paused" | "active" | "concluded" | "archived";

export interface ConsensusResult {
  reached?: boolean;
  agreement?: number;
  confidence?: number;
  final_answer?: string;
  conclusion?: string;
  supporting_agents?: string[];
  dissenting_agents?: string[];
}

export interface DebateCreateRequest {
  /** The topic or question for the debate */
  task: string;
  /** Alias for task (deprecated, use task instead) */
  question?: string;
  /** List of agent specs to participate. If empty, auto_select is used. */
  agents?: any[];
  /** Maximum number of debate rounds */
  rounds?: number;
  /** Consensus strategy to use */
  consensus?: "majority" | "unanimous" | "supermajority" | "weighted" | "hybrid" | "judge" | "none";
  /** Additional context or background information */
  context?: string;
  /** Debate protocol preset */
  debate_format?: "light" | "full";
  /** Document IDs to ground the debate in uploaded files */
  documents?: string[];
  /** Alias for documents (deprecated) */
  document_ids?: string[];
  /** Automatically select optimal agents based on topic (used when agents is empty) */
  auto_select?: boolean;
  /** Configuration for auto-selection algorithm */
  auto_select_config?: {
    primary_domain?: string;
    secondary_domains?: string[];
    required_traits?: string[];
    min_agents?: number;
    max_agents?: number;
    quality_priority?: number;
    diversity_preference?: number;
  };
  /** Enable vertical specialist injection for the task domain (default set by ARAGORA_ENABLE_VERTICALS) */
  enable_verticals?: boolean;
  /** Explicit vertical ID to inject (e.g., software, legal, healthcare) */
  vertical_id?: string;
  /** Include trending context from news/social media */
  use_trending?: boolean;
  /** Category filter for trending content */
  trending_category?: "tech" | "science" | "politics" | "business" | "health";
  /** Optional metadata for tracking and integrations */
  metadata?: Record<string, any>;
  /** Post-consensus quality pipeline configuration. When present, the server applies deterministic quality checks and repairs to the consensus answer. */
  quality_pipeline?: {
    enabled?: boolean;
    required_sections?: string[];
    output_contract_file?: string;
    quality_min_score?: number;
    practicality_min_score?: number;
  };
}

export interface DebateCreateResponse {
  /** Whether the debate was created successfully */
  success: boolean;
  /** Unique identifier for the created debate */
  debate_id?: string;
  /** Current status of the debate */
  status?: DebateStatus;
  /** The debate topic (echoed back) */
  task?: string;
  /** Agents participating in the debate */
  agents?: string[];
  /** WebSocket URL to stream debate progress */
  websocket_url?: string;
  /** Estimated debate duration in seconds */
  estimated_duration?: number;
  /** Error message if success is false */
  error?: string;
}

export interface Debate {
  debate_id?: string;
  id?: string;
  slug?: string;
  task?: string;
  /** Alias for task */
  topic?: string;
  context?: string;
  status?: DebateStatus;
  outcome?: string;
  final_answer?: string;
  consensus?: ConsensusResult;
  consensus_proof?: Record<string, any>;
  consensus_reached?: boolean;
  confidence?: number;
  rounds_used?: number;
  duration_seconds?: number;
  agents?: string[];
  rounds?: Round[];
  created_at?: string;
  completed_at?: string;
  metadata?: Record<string, any>;
}

export interface Message {
  role?: "system" | "user" | "assistant";
  content?: string;
  agent?: string;
  agent_id?: string;
  round?: number;
  timestamp?: string;
}

export interface Round {
  /** Round number (1-indexed) */
  round_number?: number;
  messages?: Message[];
  /** Agent votes for this round */
  votes?: Record<string, any>;
  /** Round summary */
  summary?: string;
}

export interface Consensus {
  reached?: boolean;
  topic?: string;
  verdict?: string;
  confidence?: number;
  participating_agents?: string[];
}

export interface SimilarDebate {
  debate_id?: string;
  topic?: string;
  /** 0-1 similarity */
  similarity_score?: number;
  verdict?: string;
  created_at?: string;
  agents?: string[];
}

export interface SimilarDebatesResponse {
  debates?: SimilarDebate[];
  query?: string;
  total?: number;
}

export interface SettledQuestion {
  question?: string;
  answer?: string;
  confidence?: number;
  debate_count?: number;
  last_debated?: string;
  supporting_debates?: string[];
}

export interface SettledQuestionsResponse {
  questions?: SettledQuestion[];
  total?: number;
  threshold?: number;
}

export interface ConsensusStats {
  total_debates?: number;
  consensus_rate?: number;
  avg_time_to_consensus_ms?: number;
  avg_rounds_to_consensus?: number;
  by_domain?: Record<string, any>;
}

export interface ConsensusDetectionData {
  debate_id?: string;
  consensus_reached?: boolean;
  confidence?: number;
  threshold?: number;
  agreement_ratio?: number;
  has_strong_consensus?: boolean;
  final_claim?: string;
  reasoning_summary?: string;
  supporting_agents?: string[];
  dissenting_agents?: string[];
  claims_count?: number;
  evidence_count?: number;
  unresolved_tensions_count?: number;
  proof?: Record<string, any>;
  checksum?: string;
}

export interface ConsensusDetectionResponse {
  data: ConsensusDetectionData;
}

export interface ConsensusStatusData {
  debate_id?: string;
  consensus_reached?: boolean;
  confidence?: number;
  agreement_ratio?: number;
  has_strong_consensus?: boolean;
  final_claim?: string;
  supporting_agents?: string[];
  dissenting_agents?: string[];
  claims_count?: number;
  dissents_count?: number;
  unresolved_tensions_count?: number;
  partial_consensus?: Record<string, any>;
  proof?: Record<string, any>;
  checksum?: string;
}

export interface ConsensusStatusResponse {
  data: ConsensusStatusData;
}

export interface DissentingView {
  debate_id?: string;
  agent?: string;
  position?: string;
  reasoning?: string;
  strength_score?: number;
  created_at?: string;
}

export interface DissentingViewsResponse {
  dissents?: DissentingView[];
  total?: number;
}

export interface ContrarianView {
  topic?: string;
  consensus_position?: string;
  contrarian_position?: string;
  agent?: string;
  argument_strength?: number;
}

export interface ContrarianViewsResponse {
  views?: ContrarianView[];
  total?: number;
}

export interface RiskWarning {
  type?: "low_confidence" | "shifting" | "contradictory" | "bias";
  topic?: string;
  description?: string;
  severity?: "low" | "medium" | "high";
  debate_ids?: string[];
}

export interface RiskWarningsResponse {
  warnings?: RiskWarning[];
  total?: number;
}

export interface DomainConsensusResponse {
  domain?: string;
  total_debates?: number;
  consensus_rate?: number;
  settled_questions?: SettledQuestion[];
  top_agents?: {
    agent?: string;
    contribution_count?: number;
  }[];
}

export interface DebateSummary {
  debate_id: string;
  summary: string;
  confidence?: number;
  consensus_reached?: boolean;
}

export interface BeliefCrux {
  id?: string;
  /** The crux proposition */
  proposition?: string;
  /** Importance score 0-1 */
  importance?: number;
  agents_for?: string[];
  agents_against?: string[];
  /** How resolving this crux would affect the debate */
  resolution_impact?: string;
}

export interface BeliefCruxesResponse {
  debate_id?: string;
  cruxes?: BeliefCrux[];
  total?: number;
}

export interface LoadBearingClaim {
  id?: string;
  claim?: string;
  agent?: string;
  /** Number of arguments that depend on this claim */
  dependents_count?: number;
  confidence?: number;
  evidence?: string[];
}

export interface LoadBearingClaimsResponse {
  debate_id?: string;
  claims?: LoadBearingClaim[];
  total?: number;
}

export interface BeliefGraphStats {
  debate_id?: string;
  node_count?: number;
  edge_count?: number;
  max_depth?: number;
  clustering_coefficient?: number;
  most_connected_claims?: {
    claim?: string;
    connections?: number;
  }[];
}

export interface Calibration {
  agent?: string;
  /** Calibration score (0-1) */
  score?: number;
  bucket_stats?: Record<string, any>[];
  overconfidence_index?: number;
}

export interface Relationship {
  agent_a?: string;
  agent_b?: string;
  alliance_score?: number;
  rivalry_score?: number;
  total_interactions?: number;
}

export interface OAuthProvider {
  /** Provider identifier (e.g., 'google', 'github') */
  id: string;
  /** Display name for the provider */
  name: string;
}

export interface OAuthProviders {
  /** List of available OAuth providers */
  providers: OAuthProvider[];
}

export interface Workspace {
  /** Workspace ID */
  id: string;
  /** Parent organization ID */
  organization_id: string;
  /** Workspace name */
  name: string;
  created_at?: string;
  created_by?: string;
  /** Whether workspace data is encrypted */
  encrypted?: boolean;
  /** Data retention period in days */
  retention_days?: number;
  /** Data sensitivity level */
  sensitivity_level?: string;
  document_count?: number;
  storage_bytes?: number;
}

export interface WorkspaceList {
  workspaces: Workspace[];
  total: number;
}

export interface RetentionPolicy {
  id?: string;
  name?: string;
  retention_days?: number;
  data_types?: string[];
  enabled?: boolean;
  created_at?: string;
}

export interface RetentionPolicyList {
  policies?: RetentionPolicy[];
  total?: number;
}

export interface StepDefinition {
  id?: string;
  name?: string;
  type?: string;
  config?: Record<string, any>;
  depends_on?: string[];
}

export interface TransitionRule {
  from_step?: string;
  to_step?: string;
  condition?: string;
}

export interface Workflow {
  id?: string;
  name?: string;
  description?: string;
  version?: string;
  status?: string;
  steps?: StepDefinition[];
  transitions?: TransitionRule[];
  created_at?: string;
  updated_at?: string;
}

export interface WorkflowList {
  workflows?: Workflow[];
  total?: number;
}

export interface WorkflowUpdate {
  name?: string;
  description?: string;
  steps?: StepDefinition[];
  transitions?: TransitionRule[];
}

export interface WorkflowTemplate {
  id?: string;
  name?: string;
  description?: string;
  category?: string;
  steps?: StepDefinition[];
  parameters?: Record<string, any>;
}

export interface WorkflowTemplateList {
  templates?: WorkflowTemplate[];
  total?: number;
}

export interface ExecutionList {
  executions?: Record<string, any>[];
  total?: number;
}

export interface DecisionReceipt {
  /** Receipt ID */
  id: string;
  /** Associated debate ID */
  debate_id: string;
  /** Final verdict */
  verdict: string;
  /** Confidence score (0-1) */
  confidence?: number;
  consensus_reached?: boolean;
  participating_agents?: string[];
  dissenting_agents?: string[];
  evidence?: Record<string, any>[];
  reasoning?: string;
  /** Receipt integrity hash */
  hash?: string;
  created_at?: string;
  metadata?: Record<string, any>;
}

export interface ReceiptList {
  receipts: DecisionReceipt[];
  total: number;
  offset?: number;
  limit?: number;
  has_more?: boolean;
}

export interface RiskHeatmap {
  /** Heatmap ID */
  id: string;
  /** Associated gauntlet ID */
  gauntlet_id?: string;
  /** Risk categories */
  categories: string[];
  /** Risk scores per category */
  scores: number[];
  /** 2D risk matrix */
  matrix?: number[][];
  /** Overall risk score */
  overall_risk?: number;
  created_at?: string;
  metadata?: Record<string, any>;
}

export interface HeatmapList {
  heatmaps: RiskHeatmap[];
  total: number;
  offset?: number;
  limit?: number;
}

export interface PatternTemplate {
  /** Pattern template ID */
  id: string;
  /** Pattern name */
  name: string;
  /** Pattern description */
  description?: string;
  pattern_type: "hive_mind" | "map_reduce" | "review_cycle";
  /** Pattern parameters schema */
  parameters?: Record<string, any>;
  /** Example configuration */
  example_config?: Record<string, any>;
  created_at?: string;
}

export interface PatternTemplateList {
  templates: PatternTemplate[];
  total: number;
}

export interface CheckpointMetadata {
  /** Checkpoint ID */
  id: string;
  /** Associated debate ID */
  debate_id?: string;
  /** Associated workflow ID */
  workflow_id?: string;
  /** Checkpoint name */
  name?: string;
  description?: string;
  /** Checkpoint state data */
  state?: Record<string, any>;
  round_number?: number;
  created_at: string;
  created_by?: string;
  size_bytes?: number;
}

export interface CheckpointList {
  checkpoints: CheckpointMetadata[];
  total: number;
  offset?: number;
  limit?: number;
}

export interface RestoreResult {
  success: boolean;
  checkpoint_id: string;
  debate_id?: string;
  workflow_id?: string;
  restored_at?: string;
  state_restored?: boolean;
  message?: string;
}

export interface DecisionExplanation {
  /** Debate ID */
  debate_id: string;
  /** Natural language narrative */
  narrative: string;
  /** Overall confidence (0-1) */
  confidence?: number;
  /** Contributing factors */
  factors?: {
    name?: string;
    contribution?: number;
    description?: string;
    type?: string;
  }[];
  /** What-if scenarios */
  counterfactuals?: {
    scenario?: string;
    outcome?: string;
    probability?: number;
  }[];
  /** Decision provenance chain */
  provenance?: {
    step?: number;
    action?: string;
    agent?: string;
    confidence?: number;
    timestamp?: string;
  }[];
  generated_at?: string;
}

export interface EvidenceLink {
  id: string;
  content: string;
  source: string;
  relevance_score: number;
  quality_scores?: Record<string, any>;
  cited_by?: string[];
  grounding_type?: string;
  timestamp?: string;
  metadata?: Record<string, any>;
}

export interface EvidenceChain {
  debate_id: string;
  evidence_count: number;
  evidence_quality_score?: number;
  evidence: EvidenceLink[];
}

export interface VotePivot {
  agent: string;
  choice: string;
  confidence: number;
  weight: number;
  reasoning_summary: string;
  influence_score?: number;
  calibration_adjustment?: number | null;
  elo_rating?: number | null;
  flip_detected?: boolean;
  metadata?: Record<string, any>;
}

export interface VotePivots {
  debate_id: string;
  total_votes?: number;
  pivotal_votes?: number;
  agent_agreement_score?: number;
  votes: VotePivot[];
}

export interface Counterfactual {
  condition: string;
  outcome_change: string;
  likelihood: number;
  sensitivity: number;
  affected_agents?: string[];
  metadata?: Record<string, any>;
}

export interface Counterfactuals {
  debate_id: string;
  counterfactual_count?: number;
  counterfactuals: Counterfactual[];
}

export interface ExplainabilityBatch {
  batch_id: string;
  status: string;
  total_debates: number;
  status_url?: string;
  results_url?: string;
}

export interface ExplainabilityBatchStatus {
  batch_id: string;
  status: string;
  total_debates: number;
  processed_count?: number;
  success_count?: number;
  error_count?: number;
  created_at?: number;
  started_at?: number | null;
  completed_at?: number | null;
  progress_pct?: number;
}

export interface BatchDebateResult {
  debate_id: string;
  status: string;
  processing_time_ms?: number;
  explanation?: Record<string, any>;
  error?: string;
}

export interface ExplainabilityBatchResults {
  batch_id: string;
  status: string;
  total_debates: number;
  processed_count?: number;
  success_count?: number;
  error_count?: number;
  created_at?: number;
  started_at?: number | null;
  completed_at?: number | null;
  progress_pct?: number;
  results: BatchDebateResult[];
  pagination?: {
    offset?: number;
    limit?: number;
    total?: number;
    has_more?: boolean;
  };
}

export interface ControlPlaneAgent {
  agent_id: string;
  capabilities: string[];
  status: string;
  model?: string;
  provider?: string;
  metadata?: Record<string, any>;
  registered_at?: number;
  last_heartbeat?: number;
  current_task_id?: string | null;
  tasks_completed?: number;
  tasks_failed?: number;
  avg_latency_ms?: number;
  region_id?: string;
  available_regions?: string[];
  region_latency_ms?: Record<string, any>;
  last_heartbeat_by_region?: Record<string, any>;
}

export interface ControlPlaneAgentList {
  agents: ControlPlaneAgent[];
  total: number;
}

export interface ControlPlaneTask {
  id: string;
  task_type: string;
  payload?: Record<string, any>;
  required_capabilities?: string[];
  status: string;
  priority?: string;
  created_at?: number;
  assigned_at?: number | null;
  started_at?: number | null;
  completed_at?: number | null;
  assigned_agent?: string | null;
  timeout_seconds?: number | null;
  max_retries?: number;
  retries?: number;
  result?: Record<string, any> | null;
  error?: string | null;
  metadata?: Record<string, any>;
  target_region?: string | null;
  fallback_regions?: string[];
  assigned_region?: string | null;
  region_routing_mode?: string;
  origin_region?: string | null;
}

export interface ControlPlaneTaskCreated {
  task_id: string;
}

export interface ControlPlaneTaskClaimResponse {
  task?: any;
}

export interface ControlPlaneQueueJob {
  id?: string;
  type?: string;
  name?: string;
  status?: string;
  progress?: number;
  started_at?: string | null;
  created_at?: string | null;
  document_count?: number;
  agents_assigned?: string[];
  priority?: string;
}

export interface ControlPlaneQueue {
  jobs: ControlPlaneQueueJob[];
  total: number;
}

export interface ControlPlaneMetrics {
  active_jobs?: number;
  queued_jobs?: number;
  completed_jobs?: number;
  agents_available?: number;
  agents_busy?: number;
  total_agents?: number;
  documents_processed_today?: number;
  audits_completed_today?: number;
  tokens_used_today?: number;
}

export interface ControlPlaneStats {
  scheduler?: Record<string, any>;
  registry?: Record<string, any>;
}

export interface ControlPlaneHealth {
  status?: string;
  agents?: Record<string, any>;
}

export interface AgentRegistration {
  agent_id?: string;
  capabilities?: string[];
  model?: string;
  provider?: string;
  registered_at?: string;
  status?: string;
}

export interface TaskStatus {
  task_id?: string;
  status?: string;
  progress?: number;
  started_at?: string;
  completed_at?: string;
  result?: Record<string, any> | null;
  error?: string | null;
}

export interface PolicyEvaluation {
  policy_id?: string;
  allowed?: boolean;
  reason?: string;
  conditions_met?: string[];
  evaluated_at?: string;
}

export interface VulnerabilityReference {
  url?: string;
  source?: string;
  tags?: string[];
}

export interface VulnerabilityFinding {
  id?: string;
  title?: string;
  description?: string;
  severity?: string;
  cvss_score?: number | null;
  package_name?: string | null;
  package_ecosystem?: string | null;
  vulnerable_versions?: string[];
  patched_versions?: string[];
  source?: string;
  references?: VulnerabilityReference[];
  cwe_ids?: string[];
  fix_available?: boolean;
  recommended_version?: string | null;
}

export interface DependencyInfo {
  name?: string;
  version?: string;
  ecosystem?: string;
  direct?: boolean;
  dev_dependency?: boolean;
  license?: string | null;
  vulnerabilities?: VulnerabilityFinding[];
  has_vulnerabilities?: boolean;
  highest_severity?: string | null;
}

export interface CodebaseScanSummary {
  total_dependencies?: number;
  vulnerable_dependencies?: number;
  critical_count?: number;
  high_count?: number;
  medium_count?: number;
  low_count?: number;
}

export interface CodebaseScanResult {
  scan_id?: string;
  repository?: string;
  branch?: string | null;
  commit_sha?: string | null;
  started_at?: string;
  completed_at?: string;
  status?: string;
  error?: string | null;
  dependencies?: DependencyInfo[];
  vulnerabilities?: VulnerabilityFinding[];
  summary?: CodebaseScanSummary;
}

export interface CodebaseScanStartResponse {
  success?: boolean;
  scan_id?: string;
  status?: string;
  repository?: string;
}

export interface CodebaseScanResultResponse {
  success?: boolean;
  scan_result?: CodebaseScanResult;
}

export interface CodebaseScanListResponse {
  success?: boolean;
  scans?: Record<string, any>[];
  total?: number;
  limit?: number;
  offset?: number;
}

export interface CodebaseVulnerabilityListResponse {
  success?: boolean;
  vulnerabilities?: VulnerabilityFinding[];
  total?: number;
  limit?: number;
  offset?: number;
  scan_id?: string;
}

export interface CodebasePackageVulnerabilityResponse {
  success?: boolean;
  package?: string;
  ecosystem?: string;
  version?: string | null;
  vulnerabilities?: VulnerabilityFinding[];
  total?: number;
}

export interface CodebaseCVEResponse {
  success?: boolean;
  vulnerability?: VulnerabilityFinding;
}

export interface CodebaseMetricsStartResponse {
  success?: boolean;
  analysis_id?: string;
  status?: string;
  repository?: string;
}

export interface CodebaseMetricsReportResponse {
  success?: boolean;
  report?: Record<string, any>;
}

export interface CodebaseHotspot {
  file_path?: string;
  function_name?: string | null;
  class_name?: string | null;
  start_line?: number;
  end_line?: number;
  complexity?: number;
  lines_of_code?: number;
  risk_score?: number;
}

export interface CodebaseHotspotListResponse {
  success?: boolean;
  hotspots?: CodebaseHotspot[];
  total?: number;
  analysis_id?: string;
}

export interface CodebaseDuplicateListResponse {
  success?: boolean;
  duplicates?: Record<string, any>[];
  total?: number;
  analysis_id?: string;
}

export interface CodebaseFileMetricsResponse {
  success?: boolean;
  file?: Record<string, any>;
  analysis_id?: string;
}

export interface CodebaseMetricsHistoryResponse {
  success?: boolean;
  analyses?: Record<string, any>[];
  total?: number;
  limit?: number;
  offset?: number;
}

export interface CodebaseDependencyAnalysisRequest {
  repository: string;
  branch?: string;
  include_dev?: boolean;
  ecosystems?: string[];
}

export interface CodebaseDependencyAnalysisResponse {
  success?: boolean;
  analysis_id?: string;
  status?: string;
}

export interface CodebaseDependencyScanRequest {
  repository: string;
  branch?: string;
  severity_threshold?: string;
}

export interface CodebaseDependencyScanResponse {
  success?: boolean;
  scan_id?: string;
  status?: string;
}

export interface CodebaseLicenseCheckRequest {
  repository: string;
  branch?: string;
  allowed_licenses?: string[];
  blocked_licenses?: string[];
}

export interface CodebaseLicenseCheckResponse {
  success?: boolean;
  check_id?: string;
  status?: string;
}

export interface CodebaseSBOMRequest {
  repository: string;
  branch?: string;
  format?: "spdx" | "cyclonedx";
  include_dev?: boolean;
}

export interface CodebaseSBOMResponse {
  success?: boolean;
  sbom_id?: string;
  format?: string;
}

export interface CodebaseSecretsScanRequest {
  repository: string;
  branch?: string;
  include_history?: boolean;
  patterns?: string[];
}

export interface CodebaseSecretsScanStartResponse {
  success?: boolean;
  scan_id?: string;
  status?: string;
  repository?: string;
  include_history?: boolean;
}

export interface CodebaseSecretsScanResultResponse {
  success?: boolean;
  scan_id?: string;
  findings?: Record<string, any>[];
  total?: number;
}

export interface CodebaseSecretsListResponse {
  success?: boolean;
  secrets?: Record<string, any>[];
  total?: number;
}

export interface CodebaseSecretsScanListResponse {
  success?: boolean;
  scans?: Record<string, any>[];
  total?: number;
  limit?: number;
  offset?: number;
}

export interface DecisionRequest {
  request_id?: string;
  content: string;
  decision_type?: string;
  source?: string;
  response_channels?: Record<string, any>[];
  context?: Record<string, any>;
  config?: Record<string, any>;
  priority?: string;
  attachments?: Record<string, any>[];
  evidence?: Record<string, any>[];
  documents?: string[];
}

export interface DecisionResult {
  request_id: string;
  decision_type: string;
  answer: string;
  confidence: number;
  consensus_reached?: boolean;
  reasoning?: string | null;
  evidence_used?: Record<string, any>[];
  agent_contributions?: Record<string, any>[];
  duration_seconds?: number;
  completed_at?: string;
  success?: boolean;
  error?: string | null;
}

export interface DecisionStatus {
  request_id: string;
  status: string;
  completed_at?: string | null;
}

export interface DecisionSummary {
  request_id: string;
  status?: string;
  completed_at?: string | null;
}

export interface DecisionList {
  decisions: DecisionSummary[];
  total: number;
}

export interface DeliberationRequest {
  request_id?: string;
  content: string;
  decision_type?: string;
  async?: boolean;
  priority?: string;
  timeout_seconds?: number;
  required_capabilities?: string[];
  response_channels?: Record<string, any>[];
  metadata?: Record<string, any>;
}

export interface DeliberationQueuedResponse {
  task_id: string;
  request_id: string;
  status: string;
}

export interface DeliberationSyncResponse {
  request_id: string;
  status: string;
  decision_type?: string;
  answer?: string;
  confidence?: number;
  consensus_reached?: boolean;
  reasoning?: string | null;
  evidence_used?: Record<string, any>[];
  duration_seconds?: number;
  error?: string | null;
}

export interface DeliberationRecord {
  request_id: string;
  status: string;
  result?: DecisionResult;
  completed_at?: string;
  error?: string | null;
  metrics?: Record<string, any>;
}

export interface DeliberationStatus {
  request_id: string;
  status: string;
  completed_at?: string | null;
}

export interface GitHubReviewComment {
  id: string;
  file_path: string;
  line: number;
  body: string;
  side?: string;
  suggestion?: string | null;
  severity?: string;
  category?: string;
}

export interface GitHubPRReviewResult {
  review_id: string;
  pr_number: number;
  repository: string;
  status: string;
  verdict?: string | null;
  summary?: string | null;
  comments: GitHubReviewComment[];
  started_at: string;
  completed_at?: string;
  error?: string | null;
  metrics?: Record<string, any>;
}

export interface GitHubPRDetails {
  number: number;
  title: string;
  body?: string;
  state: string;
  author: string;
  base_branch: string;
  head_branch: string;
  changed_files?: {
    filename?: string;
    status?: string;
    additions?: number;
    deletions?: number;
    patch?: string;
  }[];
  commits?: Record<string, any>[];
  labels?: string[];
  created_at?: string;
  updated_at?: string;
}

export interface GitHubPRReviewTriggerRequest {
  /** owner/repo */
  repository: string;
  pr_number: number;
  review_type?: "comprehensive" | "quick" | "security";
  workspace_id?: string;
}

export interface GitHubPRReviewTriggerResponse {
  success: boolean;
  review_id?: string;
  status?: string;
  pr_number?: number;
  repository?: string;
  error?: string | null;
}

export interface GitHubPRDetailsResponse {
  success: boolean;
  pr?: GitHubPRDetails;
  error?: string | null;
}

export interface GitHubPRReviewStatusResponse {
  success: boolean;
  review?: GitHubPRReviewResult;
  error?: string | null;
}

export interface GitHubPRReviewListResponse {
  success: boolean;
  reviews: GitHubPRReviewResult[];
  total: number;
  error?: string | null;
}

export interface GitHubPRSubmitReviewRequest {
  /** owner/repo */
  repository: string;
  event: "APPROVE" | "REQUEST_CHANGES" | "COMMENT";
  body?: string;
  comments?: {
    path: string;
    position: number;
    body: string;
  }[];
}

export interface GitHubPRSubmitReviewResponse {
  success: boolean;
  demo?: boolean;
  data?: Record<string, any>;
  error?: string | null;
}

export interface CostBreakdownItem {
  name?: string;
  cost?: number;
  percentage?: number;
}

export interface CostDailyItem {
  date?: string;
  cost?: number;
  tokens?: number;
}

export interface CostAlert {
  id?: string;
  type?: string;
  message?: string;
  severity?: string;
  timestamp?: string;
}

export interface CostSummaryResponse {
  totalCost?: number;
  budget?: number;
  tokensUsed?: number;
  apiCalls?: number;
  lastUpdated?: string;
  costByProvider?: CostBreakdownItem[];
  costByFeature?: CostBreakdownItem[];
  dailyCosts?: CostDailyItem[];
  alerts?: CostAlert[];
}

export interface CostBreakdownResponse {
  groupBy?: string;
  breakdown?: CostBreakdownItem[];
  total?: number;
}

export interface CostTimelineResponse {
  timeline?: CostDailyItem[];
  total?: number;
  average?: number;
}

export interface CostAlertsResponse {
  alerts?: CostAlert[];
}

export interface CostBudgetRequest {
  budget: number;
  workspace_id?: string;
}

export interface CostBudgetResponse {
  success: boolean;
  budget?: number;
  workspace_id?: string;
}

export interface CostDismissAlertResponse {
  success: boolean;
}

export interface CostUsageResponse {
  workspace_id?: string;
  time_range?: string;
  group_by?: string;
  total_cost_usd?: number;
  total_tokens_in?: number;
  total_tokens_out?: number;
  total_api_calls?: number;
  usage?: {
    name?: string;
    cost_usd?: number;
    api_calls?: number;
  }[];
  period_start?: string;
  period_end?: string;
}

export interface CostBudgetsListResponse {
  budgets: {
    id?: string;
    workspace_id?: string;
    name?: string;
    monthly_limit_usd?: number | null;
    daily_limit_usd?: number | null;
    current_monthly_spend?: number;
    current_daily_spend?: number;
    active?: boolean;
  }[];
  count: number;
  workspace_id?: string;
}

export interface CostBudgetCreateRequest {
  workspace_id?: string;
  name?: string;
  monthly_limit_usd: number;
  daily_limit_usd?: number;
  /** Alert threshold percentages (e.g. [50, 75, 90, 100]) */
  alert_thresholds?: number[];
}

export interface CostConstraintCheckResponse {
  allowed: boolean;
  reason: string;
  workspace_id?: string;
  estimated_cost_usd?: number;
  operation?: string;
  remaining_monthly_budget?: number | null;
}

export interface CostEstimateResponse {
  estimated_cost_usd: number;
  breakdown?: {
    input_tokens?: number;
    output_tokens?: number;
    input_cost_usd?: number;
    output_cost_usd?: number;
  };
  pricing?: {
    model?: string;
    provider?: string;
    input_per_1m?: number;
    output_per_1m?: number;
  };
  operation?: string;
}

export interface CostForecastDetailedResponse {
  workspace_id?: string;
  forecast_days?: number;
  summary?: Record<string, any>;
  daily_forecasts?: {
    date?: string;
    projected_cost_usd?: number;
    confidence_low?: number;
    confidence_high?: number;
  }[];
  confidence_level?: number;
}

export interface CostRecommendationsDetailedResponse {
  recommendations?: {
    id?: string;
    type?: string;
    description?: string;
    estimated_savings_usd?: number;
    implementation_steps?: string[];
    difficulty?: string;
    time_to_implement?: string;
  }[];
  count?: number;
  summary?: Record<string, any>;
  workspace_id?: string;
  total_potential_savings_usd?: number;
}

export interface CostAlertCreateResponse {
  success: boolean;
  alert?: {
    id?: string;
    workspace_id?: string;
    name?: string;
    type?: string;
    threshold?: number;
    notification_channels?: string[];
    active?: boolean;
    created_at?: string;
  };
}

export type BudgetPeriod = "daily" | "weekly" | "monthly" | "quarterly" | "annual" | "unlimited";

export type BudgetStatus = "active" | "warning" | "critical" | "exceeded" | "suspended" | "paused" | "closed";

export type BudgetAction = "notify" | "warn" | "soft_limit" | "hard_limit" | "suspend";

export interface BudgetThreshold {
  /** Threshold percentage (0.0 - 1.0) */
  percentage: number;
  action: BudgetAction;
}

export interface Budget {
  id: string;
  workspace_id: string;
  name: string;
  description?: string | null;
  limit_usd: number;
  period: BudgetPeriod;
  status: BudgetStatus;
  current_spend_usd?: number;
  current_period_start?: string;
  current_period_end?: string;
  thresholds?: BudgetThreshold[];
  scope?: Record<string, any>;
  created_at?: string;
  updated_at?: string;
  created_by?: string;
}

export interface BudgetCreateRequest {
  name: string;
  description?: string;
  limit_usd: number;
  period: BudgetPeriod;
  thresholds?: BudgetThreshold[];
  scope?: Record<string, any>;
}

export interface BudgetUpdateRequest {
  name?: string;
  description?: string;
  limit_usd?: number;
  period?: BudgetPeriod;
  status?: BudgetStatus;
  thresholds?: BudgetThreshold[];
}

export interface BudgetListResponse {
  budgets: Budget[];
  total: number;
  offset?: number;
  limit?: number;
}

export interface BudgetSummary {
  total_budget_usd?: number;
  total_spend_usd?: number;
  active_budgets?: number;
  warning_budgets?: number;
  exceeded_budgets?: number;
  utilization_percentage?: number;
  trend?: "increasing" | "stable" | "decreasing";
}

export interface BudgetCheckRequest {
  operation_type: string;
  estimated_cost_usd?: number;
  model?: string;
  tokens?: number;
}

export interface BudgetCheckResponse {
  allowed: boolean;
  budget_id?: string | null;
  remaining_usd?: number | null;
  current_utilization?: number | null;
  reason?: string | null;
}

export interface BudgetAlert {
  id: string;
  budget_id: string;
  budget_name: string;
  threshold_percentage: number;
  actual_percentage?: number;
  action_taken: BudgetAction;
  message?: string;
  created_at?: string;
  acknowledged?: boolean;
  acknowledged_at?: string;
  acknowledged_by?: string | null;
}

export interface BudgetAlertListResponse {
  alerts: BudgetAlert[];
  total: number;
  unacknowledged_count?: number;
}

export interface BudgetOverrideRequest {
  budget_id: string;
  override_limit_usd: number;
  duration_hours?: number;
  reason: string;
}

export interface BudgetOverrideResponse {
  override_added: boolean;
  budget_id: string;
  user_id: string;
  duration_hours?: number | null;
}

export interface SharedInbox {
  id?: string;
  workspace_id?: string;
  name?: string;
  description?: string | null;
  email_address?: string | null;
  connector_type?: string | null;
  team_members?: string[];
  admins?: string[];
  message_count?: number;
  unread_count?: number;
  settings?: Record<string, any>;
  created_at?: string;
  updated_at?: string;
  created_by?: string | null;
}

export interface SharedInboxMessage {
  id?: string;
  inbox_id?: string;
  email_id?: string;
  subject?: string;
  from_address?: string;
  to_addresses?: string[];
  snippet?: string;
  received_at?: string;
  status?: string;
  assigned_to?: string | null;
  tags?: string[];
  priority?: string | null;
}

export interface SharedInboxResponse {
  success: boolean;
  inbox?: SharedInbox;
  error?: string | null;
}

export interface SharedInboxListResponse {
  success: boolean;
  inboxes: SharedInbox[];
  total: number;
}

export interface SharedInboxMessageListResponse {
  success: boolean;
  messages: SharedInboxMessage[];
  total: number;
  limit?: number;
  offset?: number;
}

export interface SharedInboxMessageResponse {
  success: boolean;
  message?: SharedInboxMessage;
  error?: string | null;
}

export interface SharedInboxCreateRequest {
  workspace_id: string;
  name: string;
  description?: string;
  email_address?: string;
  connector_type?: string;
  team_members?: string[];
  admins?: string[];
  settings?: Record<string, any>;
}

export interface SharedInboxAssignRequest {
  assigned_to: string;
}

export interface SharedInboxStatusRequest {
  status: string;
}

export interface SharedInboxTagRequest {
  tag: string;
}

export interface RoutingRule {
  id?: string;
  workspace_id?: string;
  name?: string;
  conditions?: Record<string, any>[];
  condition_logic?: string;
  actions?: Record<string, any>[];
  priority?: number;
  enabled?: boolean;
  description?: string | null;
  created_at?: string;
  updated_at?: string;
  created_by?: string | null;
  stats?: Record<string, any>;
}

export interface RoutingRuleResponse {
  success: boolean;
  rule?: RoutingRule;
  error?: string | null;
}

export interface RoutingRuleListResponse {
  success: boolean;
  rules: RoutingRule[];
  total: number;
  limit?: number;
  offset?: number;
}

export interface RoutingRuleDeleteResponse {
  success: boolean;
  deleted?: string;
}

export interface RoutingRuleTestResponse {
  success: boolean;
  rule_id?: string;
  match_count?: number;
  rule?: RoutingRule;
  error?: string | null;
}

export interface RoutingRuleCreateRequest {
  workspace_id: string;
  name: string;
  conditions: Record<string, any>[];
  condition_logic?: string;
  actions: Record<string, any>[];
  priority?: number;
  enabled?: boolean;
  description?: string;
}

export interface RoutingRuleUpdateRequest {
  name?: string;
  description?: string;
  conditions?: Record<string, any>[];
  condition_logic?: string;
  actions?: Record<string, any>[];
  priority?: number;
  enabled?: boolean;
}

export interface RoutingRuleTestRequest {
  workspace_id: string;
}

export interface MemoryStats {
  total_entries?: number;
  by_tier?: {
    fast?: number;
    medium?: number;
    slow?: number;
    glacial?: number;
  };
  cache_hit_rate?: number;
}

export interface MemoryEntry {
  /** Unique memory ID */
  id: string;
  /** Memory content */
  content: string;
  /** Memory tier */
  tier: "fast" | "medium" | "slow" | "glacial";
  created_at?: string;
  expires_at?: string;
  /** Relevance to query 0-1 */
  relevance_score?: number;
  metadata?: Record<string, any>;
}

export interface MemoryRetrievalResponse {
  memories?: MemoryEntry[];
  total?: number;
  tier?: string;
  query?: string;
}

export interface MemoryTierStats {
  tier?: "fast" | "medium" | "slow" | "glacial";
  count?: number;
  size_bytes?: number;
  oldest_entry?: string;
  newest_entry?: string;
  avg_age_seconds?: number;
}

export interface MemoryTierStatsResponse {
  tiers?: MemoryTierStats[];
  total_memories?: number;
  total_size_bytes?: number;
}

export interface MemoryArchiveStats {
  archived_count?: number;
  archive_size_bytes?: number;
  oldest_archive?: string;
  compression_ratio?: number;
}

export interface MemoryConsolidationResult {
  memories_processed?: number;
  memories_promoted?: number;
  memories_demoted?: number;
  duration_ms?: number;
}

export interface MemoryCleanupResult {
  memories_removed?: number;
  bytes_freed?: number;
  duration_ms?: number;
}

export interface KnowledgeNode {
  /** Unique node ID */
  id: string;
  /** Node content */
  content: string;
  /** Knowledge source type */
  source?: string;
  /** Confidence score 0-1 */
  confidence?: number;
  created_at?: string;
  updated_at?: string;
  topics?: string[];
  metadata?: Record<string, any>;
}

export interface KnowledgeQueryResult {
  items?: KnowledgeNode[];
  total?: number;
  query?: string;
  relevance_scores?: number[];
}

export interface KnowledgeStoreResult {
  id?: string;
  success?: boolean;
  source?: string;
  timestamp?: string;
}

export interface KnowledgeFact {
  id?: string;
  content?: string;
  source?: string;
  confidence?: number;
  evidence?: string[];
  contradictions?: string[];
  created_at?: string;
  verified_at?: string | null;
}

export interface KnowledgeFactList {
  facts?: KnowledgeFact[];
  total?: number;
}

export interface KnowledgeSearchResult {
  node?: KnowledgeNode;
  score?: number;
  highlights?: string[];
}

export interface KnowledgeSearchResponse {
  results?: KnowledgeSearchResult[];
  total?: number;
  query?: string;
  search_time_ms?: number;
}

export interface KnowledgeStats {
  total_nodes?: number;
  total_facts?: number;
  by_source?: Record<string, any>;
  avg_confidence?: number;
  contradiction_rate?: number;
}

export interface KnowledgeQueryResponse {
  success?: boolean;
  result?: KnowledgeQueryResult;
}

export interface DisagreementStats {
  /** Total debates analyzed */
  total_debates?: number;
  /** Debates with disagreements */
  with_disagreements?: number;
  /** Unanimous debates */
  unanimous?: number;
  /** Count by disagreement type */
  disagreement_types?: Record<string, any>;
}

export interface RoleRotationStats {
  total_rotations?: number;
  by_agent?: Record<string, any>;
}

export interface EarlyStopStats {
  total_early_stops?: number;
  by_reason?: Record<string, any>;
  average_rounds_saved?: number;
}

export interface RankingStats {
  total_agents?: number;
  average_elo?: number;
  highest_elo?: number;
  lowest_elo?: number;
  total_matches?: number;
}

export interface PositionFlip {
  debate_id?: string;
  agent?: string;
  round?: number;
  old_position?: string;
  new_position?: string;
  reason?: string;
  conviction_delta?: number;
  timestamp?: string | null;
}

export interface FlipsRecent {
  flips?: PositionFlip[];
  total?: number;
}

export interface FlipsSummary {
  total_flips?: number;
  by_agent?: Record<string, any>;
  by_debate?: Record<string, any>;
  average_conviction_delta?: number;
  /** Percentage of debates with flips */
  flip_rate?: number | null;
}

export interface Insight {
  id?: string;
  debate_id?: string;
  content?: string;
  type?: "observation" | "conclusion" | "recommendation" | null;
  confidence?: number;
  supporting_evidence?: string[];
  extracted_at?: string | null;
}

export interface InsightsRecent {
  insights?: Insight[];
  total?: number;
}

export interface InsightsDetailed {
  insights?: Insight[];
  themes?: string[];
  key_findings?: string[];
  processing_time_ms?: number;
}

export interface DebateMoment {
  id?: string;
  debate_id?: string;
  type?: "breakthrough" | "conflict" | "consensus" | "insight" | "flip" | null;
  round?: number;
  description?: string;
  participants?: string[];
  significance_score?: number;
  timestamp?: string | null;
}

export interface MomentsSummary {
  total_moments?: number;
  by_type?: Record<string, any>;
  top_debates?: {
    debate_id?: string;
    moment_count?: number;
  }[];
}

export interface MomentsTimeline {
  moments?: DebateMoment[];
  start_time?: string;
  end_time?: string;
}

export interface MomentsTrending {
  moments?: DebateMoment[];
  trending_period_hours?: number;
}

export interface MomentsByType {
  type?: string;
  moments?: DebateMoment[];
  total?: number;
}

export interface UnifiedCampaign {
  /** Platform-specific campaign ID */
  id: string;
  /** Advertising platform name */
  platform: "google_ads" | "meta_ads" | "linkedin_ads" | "microsoft_ads";
  /** Campaign name */
  name: string;
  /** Campaign status */
  status: "ENABLED" | "PAUSED" | "REMOVED";
  /** Campaign objective/goal */
  objective?: string | null;
  /** Daily budget in account currency */
  daily_budget?: number | null;
  /** Total campaign budget */
  total_budget?: number | null;
  /** Campaign start date */
  start_date?: string | null;
  /** Campaign end date */
  end_date?: string | null;
  /** When the campaign was created */
  created_at?: string | null;
  /** When the campaign was last updated */
  updated_at?: string | null;
}

export interface AnalyticsDebatesOverview {
  time_range?: string;
  total_debates?: number;
  debates_this_period?: number;
  debates_previous_period?: number;
  growth_rate?: number;
  consensus_reached?: number;
  consensus_rate?: number;
  avg_rounds?: number;
  avg_agents_per_debate?: number;
  avg_confidence?: number;
  generated_at?: string;
}

export interface AnalyticsDebateTrendPoint {
  period?: string;
  total?: number;
  consensus_reached?: number;
  consensus_rate?: number;
  avg_rounds?: number;
}

export interface AnalyticsDebatesTrends {
  time_range?: string;
  granularity?: string;
  data_points?: AnalyticsDebateTrendPoint[];
  generated_at?: string;
}

export interface AnalyticsDebateTopic {
  topic?: string;
  count?: number;
  percentage?: number;
  consensus_rate?: number;
}

export interface AnalyticsDebatesTopics {
  time_range?: string;
  topics?: AnalyticsDebateTopic[];
  total_debates?: number;
  generated_at?: string;
}

export interface AnalyticsOutcomeConfidenceBucket {
  count?: number;
  consensus_rate?: number;
}

export interface AnalyticsDebatesOutcomes {
  time_range?: string;
  outcomes?: {
    consensus?: number;
    majority?: number;
    dissent?: number;
    no_resolution?: number;
  };
  total_debates?: number;
  by_confidence?: Record<string, any>;
  generated_at?: string;
}

export interface AnalyticsLeaderboardEntry {
  rank?: number;
  agent_name?: string;
  elo?: number;
  wins?: number;
  losses?: number;
  draws?: number;
  win_rate?: number;
  games_played?: number;
  calibration_score?: number;
}

export interface AnalyticsAgentsLeaderboard {
  leaderboard?: AnalyticsLeaderboardEntry[];
  total_agents?: number;
  domain?: string;
  generated_at?: string;
}

export interface AnalyticsDomainPerformanceEntry {
  elo?: number;
  wins?: number;
  losses?: number;
}

export interface AnalyticsEloHistoryPoint {
  timestamp?: string;
  elo?: number;
}

export interface AnalyticsAgentPerformance {
  agent_id?: string;
  agent_name?: string;
  time_range?: string;
  elo?: number;
  elo_change?: number;
  rank?: number;
  wins?: number;
  losses?: number;
  draws?: number;
  win_rate?: number;
  games_played?: number;
  debates_count?: number;
  consensus_contribution_rate?: number;
  calibration_score?: number;
  calibration_accuracy?: number;
  domain_performance?: Record<string, any>;
  recent_matches?: Record<string, any>[];
  elo_history?: AnalyticsEloHistoryPoint[];
  generated_at?: string;
}

export interface AnalyticsAgentComparisonEntry {
  agent_name?: string;
  elo?: number;
  wins?: number;
  losses?: number;
  draws?: number;
  win_rate?: number;
  games_played?: number;
  calibration_score?: number;
  error?: string;
}

export interface AnalyticsAgentsComparison {
  agents?: string[];
  comparison?: AnalyticsAgentComparisonEntry[];
  head_to_head?: Record<string, any>;
  generated_at?: string;
}

export interface AnalyticsAgentTrendPoint {
  period?: string;
  elo?: number;
  games?: number;
}

export interface AnalyticsAgentsTrends {
  agents?: string[];
  time_range?: string;
  granularity?: string;
  trends?: Record<string, any>;
  generated_at?: string;
}

export interface AnalyticsTokenSummary {
  total_tokens_in?: number;
  total_tokens_out?: number;
  total_tokens?: number;
  avg_tokens_per_day?: number;
}

export interface AnalyticsUsageTokens {
  org_id?: string;
  time_range?: string;
  granularity?: string;
  summary?: AnalyticsTokenSummary;
  trends?: {
    period?: string;
    tokens_in?: number;
    tokens_out?: number;
  }[];
  by_agent?: Record<string, any>;
  by_model?: Record<string, any>;
  message?: string;
  generated_at?: string;
}

export interface AnalyticsCostSummary {
  total_cost_usd?: string;
  avg_cost_per_day?: string;
  avg_cost_per_debate?: string;
  total_api_calls?: number;
}

export interface AnalyticsUsageCosts {
  org_id?: string;
  time_range?: string;
  summary?: AnalyticsCostSummary;
  by_provider?: Record<string, any>;
  by_model?: Record<string, any>;
  message?: string;
  generated_at?: string;
}

export interface AnalyticsActiveUserCounts {
  daily?: number;
  weekly?: number;
  monthly?: number;
}

export interface AnalyticsUserGrowth {
  new_users?: number;
  churned_users?: number;
  net_growth?: number;
}

export interface AnalyticsActivityDistribution {
  power_users?: number;
  regular_users?: number;
  occasional_users?: number;
}

export interface AnalyticsActiveUsers {
  org_id?: string;
  time_range?: string;
  active_users?: AnalyticsActiveUserCounts;
  user_growth?: AnalyticsUserGrowth;
  activity_distribution?: AnalyticsActivityDistribution;
  message?: string;
  generated_at?: string;
}

export interface DebateJoinRequest {
  /** Role in the debate */
  role?: "observer" | "participant" | "moderator";
  /** Display name shown to other participants */
  display_name?: string;
}

export interface DebateVoteRequest {
  /** The position being voted on */
  position: string;
  /** Vote intensity/conviction (1=weak, 10=strong) */
  intensity?: number;
  /** Optional reasoning for the vote */
  reasoning?: string;
}

export interface DebateSuggestionRequest {
  /** The suggestion or argument text */
  content: string;
  /** Type of suggestion */
  type?: "argument" | "question" | "evidence" | "follow_up";
  /** Optional: direct the suggestion at a specific agent */
  target_agent?: string;
}

export interface DebateUpdateRequest {
  /** Update max rounds */
  rounds?: number;
  /** Change consensus strategy */
  consensus?: "majority" | "unanimous" | "supermajority" | "weighted" | "hybrid" | "judge" | "none";
  /** Append additional context */
  context?: string;
  /** Update metadata (merged with existing) */
  metadata?: Record<string, any>;
}

export interface DebateForkRequest {
  /** Round number to branch from (1-indexed) */
  branch_point: number;
  /** New premise or constraint for the forked branch */
  new_premise?: string;
}

export interface DebateBroadcastRequest {
  /** Output format for the broadcast */
  format?: "audio" | "video";
  /** Voice mapping (agent_name -> voice_id) */
  voices?: Record<string, any>;
  /** Language code for TTS */
  language?: string;
}

export interface DebateCloneRequest {
  /** Keep the same agent lineup */
  preserveAgents?: boolean;
  /** Keep the original context and documents */
  preserveContext?: boolean;
}

export interface DebateFollowupRequest {
  /** ID of the crux claim to follow up on */
  cruxId?: string;
  /** Additional context for the follow-up */
  context?: string;
}

export interface DebateEvidenceRequest {
  /** The evidence text or URL */
  evidence: string;
  /** Source attribution */
  source?: string;
  /** Additional metadata about the evidence */
  metadata?: Record<string, any>;
}

export interface DebateVerifyClaimRequest {
  /** ID of the claim to verify */
  claim_id: string;
  /** Optional evidence to check the claim against */
  evidence?: string;
}

export interface DebateUserInputRequest {
  /** The user's input text */
  input: string;
  /** Type of user input */
  type?: "suggestion" | "vote" | "question" | "context";
}

export interface DebateCounterfactualRequest {
  /** The hypothetical condition to analyze */
  condition: string;
  /** Variables to adjust in the scenario */
  variables?: Record<string, any>;
}

export interface DebateMessageRequest {
  /** Message content */
  content: string;
  /** Message role */
  role?: "user" | "system";
}

export interface DebateBatchRequest {
  /** Array of debate creation requests */
  requests: DebateCreateRequest[];
}

export interface DebateInjectArgumentRequest {
  /** The argument or question to inject */
  content: string;
  /** Type of injection */
  type?: "argument" | "follow_up";
  /** Source identifier */
  source?: string;
  /** User ID for attribution */
  user_id?: string;
}

export interface DebateUpdateWeightsRequest {
  /** Agent name or ID */
  agent: string;
  /** Influence weight (0.0=muted, 1.0=normal, 2.0=double) */
  weight: number;
  /** User ID for audit trail */
  user_id?: string;
}

export interface DebateUpdateThresholdRequest {
  /** Consensus threshold (0.5=majority, 0.75=strong, 1.0=unanimous) */
  threshold: number;
  /** User ID for audit trail */
  user_id?: string;
}

export interface DebateCostEstimateRequest {
  /** Number of agents to participate */
  num_agents?: number;
  /** Number of debate rounds */
  num_rounds?: number;
  /** Model types to use */
  model_types?: string[];
}

export interface DebateCostEstimateResponse {
  /** Total estimated cost in USD */
  total_estimated_cost_usd: number;
  /** Cost breakdown per model */
  breakdown_by_model: {
    model?: string;
    provider?: string;
    estimated_input_tokens?: number;
    estimated_output_tokens?: number;
    input_cost_usd?: number;
    output_cost_usd?: number;
    subtotal_usd?: number;
  }[];
  /** Assumptions used for the estimate */
  assumptions?: {
    avg_input_tokens_per_round?: number;
    avg_output_tokens_per_round?: number;
    includes_system_prompt?: boolean;
  };
  num_agents?: number;
  num_rounds?: number;
}

export interface WebSocketResumeToken {
  /** Opaque token encoding the last received event position */
  resume_token: string;
  /** Debate this token belongs to */
  debate_id: string;
  /** Sequence number of last received event */
  last_seq: number;
  /** When this resume token expires */
  expires_at?: string;
}
